// AirStatsResponse.swift Generated by swagger-codegen ___SORACOM_SDK_SWIFT_SWAGGERER_CODE_GENERATION_METADATA___

import Foundation


public class AirStatsResponse: PayloadConvertible {

    public var dataTrafficStatsMap: [String:DataTrafficStats]?
    public var date: String?
    public var unixtime: Int64?

    public required init(
        dataTrafficStatsMap: [String:DataTrafficStats]? = nil, 
        date: String? = nil, 
        unixtime: Int64? = nil
    ) {
        self.dataTrafficStatsMap = dataTrafficStatsMap
        self.date = date
        self.unixtime = unixtime
        
    }

    // MARK: PayloadConvertible

    public func toPayload() -> Payload {

        let payload: Payload = [:]

        payload[.dataTrafficStatsMap] = dataTrafficStatsMap
        payload[.date] = date
        payload[.unixtime] = unixtime

        return payload;
    }

    public static func from(_ payload: Payload?) -> Self? {
        guard let payload = payload else {
            return nil
        }

        _ = payload // suppress compiler warnings when payload isn't used in generated code

        let result = self.init()

        result.dataTrafficStatsMap = payload.___SWAGGERER_POSTPROCESS_FIXME_[String:DataTrafficStats]___(.dataTrafficStatsMap)
        result.date = payload.getString(.date)
        result.unixtime = payload.getInt64(.unixtime)
        return result
    }

}

public typealias AirStatsResponseList = [AirStatsResponse]
