// APICallError.swift Generated by swagger-codegen  — Custom output templates and post-processing by CodeGeneratorForSoracomSDKSwift.Swaggerer version 0.0d1. Generated 2016-09-12T00:54:57Z

import Foundation


public class APICallError: PayloadConvertible {

    public var errorMessage: APICallErrorMessage?
    public var httpStatus: Int64?

    public required init(
        errorMessage: APICallErrorMessage? = nil, 
        httpStatus: Int64? = nil
    ) {
        self.errorMessage = errorMessage
        self.httpStatus = httpStatus
        
    }

    // MARK: PayloadConvertible

    public func toPayload() -> Payload {

        let payload: Payload = [:]

        payload[.errorMessage] = errorMessage
        payload[.httpStatus] = httpStatus

        return payload;
    }

    public static func from(_ payload: Payload?) -> Self? {
        guard let payload = payload else {
            return nil
        }

        _ = payload // suppress compiler warnings when payload isn't used in generated code

        let result = self.init()

        result.errorMessage = payload.decodeAPICallErrorMessage(.errorMessage)
        result.httpStatus = payload.decodeInt64(.httpStatus)
        return result
    }

}

public typealias APICallErrorList = [APICallError]
