// AuthResponse.swift Generated by swagger-codegen  — Custom output templates and post-processing by CodeGeneratorForSoracomSDKSwift.Swaggerer version 0.0d1. Generated 2016-09-12T00:54:57Z

import Foundation


public class AuthResponse: PayloadConvertible {

    public var apiKey: String?
    public var operatorId: String?
    public var token: String?
    public var userName: String?

    public required init(
        apiKey: String? = nil, 
        operatorId: String? = nil, 
        token: String? = nil, 
        userName: String? = nil
    ) {
        self.apiKey = apiKey
        self.operatorId = operatorId
        self.token = token
        self.userName = userName
        
    }

    // MARK: PayloadConvertible

    public func toPayload() -> Payload {

        let payload: Payload = [:]

        payload[.apiKey] = apiKey
        payload[.operatorId] = operatorId
        payload[.token] = token
        payload[.userName] = userName

        return payload;
    }

    public static func from(_ payload: Payload?) -> Self? {
        guard let payload = payload else {
            return nil
        }

        _ = payload // suppress compiler warnings when payload isn't used in generated code

        let result = self.init()

        result.apiKey = payload.decodeString(.apiKey)
        result.operatorId = payload.decodeString(.operatorId)
        result.token = payload.decodeString(.token)
        result.userName = payload.decodeString(.userName)
        return result
    }

}

public typealias AuthResponseList = [AuthResponse]
