// CreateEstimatedOrderRequest.swift Generated by swagger-codegen ___SORACOM_SDK_SWIFT_SWAGGERER_CODE_GENERATION_METADATA___

import Foundation


public class CreateEstimatedOrderRequest: PayloadConvertible {

    /** \u767A\u6CE8\u5546\u54C1\u30EA\u30B9\u30C8 */
    public var orderItemList: [OrderItemModel]?
    /** \u5546\u54C1\u767A\u9001\u5148ID */
    public var shippingAddressId: String?

    public required init(
        orderItemList: [OrderItemModel]? = nil, 
        shippingAddressId: String? = nil
    ) {
        self.orderItemList = orderItemList
        self.shippingAddressId = shippingAddressId
        
    }

    // MARK: PayloadConvertible

    public func toPayload() -> Payload {

        let payload: Payload = [:]

        payload[.orderItemList] = orderItemList
        payload[.shippingAddressId] = shippingAddressId

        return payload;
    }

    public static func from(_ payload: Payload?) -> Self? {
        guard let payload = payload else {
            return nil
        }

        _ = payload // suppress compiler warnings when payload isn't used in generated code

        let result = self.init()

        result.orderItemList = payload.___SWAGGERER_POSTPROCESS_FIXME_[OrderItemModel]___(.orderItemList)
        result.shippingAddressId = payload.getString(.shippingAddressId)
        return result
    }

}

public typealias CreateEstimatedOrderRequestList = [CreateEstimatedOrderRequest]
