// CreateGroupRequest.swift Generated by swagger-codegen ___SORACOM_SDK_SWIFT_SWAGGERER_CODE_GENERATION_METADATA___

import Foundation


public class CreateGroupRequest: PayloadConvertible {

    public var tags: Tag?

    public required init(
        tags: Tag? = nil
    ) {
        self.tags = tags
        
    }

    // MARK: PayloadConvertible

    public func toPayload() -> Payload {

        let payload: Payload = [:]

        payload[.tags] = tags

        return payload;
    }

    public static func from(_ payload: Payload?) -> Self? {
        guard let payload = payload else {
            return nil
        }

        _ = payload // suppress compiler warnings when payload isn't used in generated code

        let result = self.init()

        result.tags = payload.getTag(.tags)
        return result
    }

}

public typealias CreateGroupRequestList = [CreateGroupRequest]
