// CreditCard.swift Generated by swagger-codegen ___SORACOM_SDK_SWIFT_SWAGGERER_CODE_GENERATION_METADATA___

import Foundation


public class CreditCard: PayloadConvertible {

    public var cvc: String?
    public var expireMonth: Int64?
    public var expireYear: Int64?
    public var name: String?
    public var number: String?

    public required init(
        cvc: String? = nil, 
        expireMonth: Int64? = nil, 
        expireYear: Int64? = nil, 
        name: String? = nil, 
        number: String? = nil
    ) {
        self.cvc = cvc
        self.expireMonth = expireMonth
        self.expireYear = expireYear
        self.name = name
        self.number = number
        
    }

    // MARK: PayloadConvertible

    public func toPayload() -> Payload {

        let payload: Payload = [:]

        payload[.cvc] = cvc
        payload[.expireMonth] = expireMonth
        payload[.expireYear] = expireYear
        payload[.name] = name
        payload[.number] = number

        return payload;
    }

    public static func from(_ payload: Payload?) -> Self? {
        guard let payload = payload else {
            return nil
        }

        _ = payload // suppress compiler warnings when payload isn't used in generated code

        let result = self.init()

        result.cvc = payload.getString(.cvc)
        result.expireMonth = payload.getInt64(.expireMonth)
        result.expireYear = payload.getInt64(.expireYear)
        result.name = payload.getString(.name)
        result.number = payload.getString(.number)
        return result
    }

}

public typealias CreditCardList = [CreditCard]
