// EstimatedOrderItemModel.swift Generated by swagger-codegen ___SORACOM_SDK_SWIFT_SWAGGERER_CODE_GENERATION_METADATA___

import Foundation


public class EstimatedOrderItemModel: PayloadConvertible {

    /** \u5546\u54C1 */
    public var product: ProductModel?
    /** \u5546\u54C1\u91D1\u984D */
    public var productAmount: Double?
    /** \u8CFC\u5165\u6570 */
    public var quantity: Int64?

    public required init(
        product: ProductModel? = nil, 
        productAmount: Double? = nil, 
        quantity: Int64? = nil
    ) {
        self.product = product
        self.productAmount = productAmount
        self.quantity = quantity
        
    }

    // MARK: PayloadConvertible

    public func toPayload() -> Payload {

        let payload: Payload = [:]

        payload[.product] = product
        payload[.productAmount] = productAmount
        payload[.quantity] = quantity

        return payload;
    }

    public static func from(_ payload: Payload?) -> Self? {
        guard let payload = payload else {
            return nil
        }

        _ = payload // suppress compiler warnings when payload isn't used in generated code

        let result = self.init()

        result.product = payload.getProductModel(.product)
        result.productAmount = payload.getDouble(.productAmount)
        result.quantity = payload.getInt64(.quantity)
        return result
    }

}

public typealias EstimatedOrderItemModelList = [EstimatedOrderItemModel]
