// ExportRequest.swift Generated by swagger-codegen  — Custom output templates and post-processing by CodeGeneratorForSoracomSDKSwift.Swaggerer version 0.0d1. Generated 2016-09-12T00:54:57Z

import Foundation


public class ExportRequest: PayloadConvertible {

    public enum Period: String { 
        case Month = "month"
        case Day = "day"
        case Minutes = "minutes"
    }
    public var from: Int64?

    public var period: Period?
    public var to: Int64?

    public required init(
        from: Int64? = nil, 
        period: Period? = nil, 
        to: Int64? = nil
    ) {
        self.from = from
        self.period = period
        self.to = to
        
    }

    // MARK: PayloadConvertible

    public func toPayload() -> Payload {

        let payload: Payload = [:]

        payload[.from] = from
        payload[.period] = period
        payload[.to] = to

        return payload;
    }

    public static func from(_ payload: Payload?) -> Self? {
        guard let payload = payload else {
            return nil
        }

        _ = payload // suppress compiler warnings when payload isn't used in generated code

        let result = self.init()

        result.from = payload.decodeInt64(.from)
        result.period = payload.decodePeriod(.period)
        result.to = payload.decodeInt64(.to)
        return result
    }

}

public typealias ExportRequestList = [ExportRequest]
