// FileOutputResult.swift Generated by swagger-codegen ___SORACOM_SDK_SWIFT_SWAGGERER_CODE_GENERATION_METADATA___

import Foundation


public class FileOutputResult: PayloadConvertible {

    public var url: String?

    public required init(
        url: String? = nil
    ) {
        self.url = url
        
    }

    // MARK: PayloadConvertible

    public func toPayload() -> Payload {

        let payload: Payload = [:]

        payload[.url] = url

        return payload;
    }

    public static func from(_ payload: Payload?) -> Self? {
        guard let payload = payload else {
            return nil
        }

        _ = payload // suppress compiler warnings when payload isn't used in generated code

        let result = self.init()

        result.url = payload.getString(.url)
        return result
    }

}

public typealias FileOutputResultList = [FileOutputResult]
