// GetLatestBill.swift Generated by swagger-codegen  — Custom output templates and post-processing by CodeGeneratorForSoracomSDKSwift.Swaggerer version 0.0d1. Generated 2016-09-12T00:54:57Z

import Foundation


public class GetLatestBill: PayloadConvertible {

    /** \u91D1\u984D */
    public var amount: Int64?
    /** \u5229\u7528\u984D\u8A08\u7B97\u3092\u5B9F\u65BD\u3057\u305F\u6642\u9593 */
    public var lastEvaluatedTime: String?

    public required init(
        amount: Int64? = nil, 
        lastEvaluatedTime: String? = nil
    ) {
        self.amount = amount
        self.lastEvaluatedTime = lastEvaluatedTime
        
    }

    // MARK: PayloadConvertible

    public func toPayload() -> Payload {

        let payload: Payload = [:]

        payload[.amount] = amount
        payload[.lastEvaluatedTime] = lastEvaluatedTime

        return payload;
    }

    public static func from(_ payload: Payload?) -> Self? {
        guard let payload = payload else {
            return nil
        }

        _ = payload // suppress compiler warnings when payload isn't used in generated code

        let result = self.init()

        result.amount = payload.decodeInt64(.amount)
        result.lastEvaluatedTime = payload.decodeString(.lastEvaluatedTime)
        return result
    }

}

public typealias GetLatestBillList = [GetLatestBill]
