// Group.swift Generated by swagger-codegen ___SORACOM_SDK_SWIFT_SWAGGERER_CODE_GENERATION_METADATA___

import Foundation


public class Group: PayloadConvertible {

    public var configuration: Map?
    public var createdTime: Int64?
    public var groupId: String?
    public var lastModifiedTime: Int64?
    public var operatorId: String?
    public var tags: Tag?

    public required init(
        configuration: Map? = nil, 
        createdTime: Int64? = nil, 
        groupId: String? = nil, 
        lastModifiedTime: Int64? = nil, 
        operatorId: String? = nil, 
        tags: Tag? = nil
    ) {
        self.configuration = configuration
        self.createdTime = createdTime
        self.groupId = groupId
        self.lastModifiedTime = lastModifiedTime
        self.operatorId = operatorId
        self.tags = tags
        
    }

    // MARK: PayloadConvertible

    public func toPayload() -> Payload {

        let payload: Payload = [:]

        payload[.configuration] = configuration
        payload[.createdTime] = createdTime
        payload[.groupId] = groupId
        payload[.lastModifiedTime] = lastModifiedTime
        payload[.operatorId] = operatorId
        payload[.tags] = tags

        return payload;
    }

    public static func from(_ payload: Payload?) -> Self? {
        guard let payload = payload else {
            return nil
        }

        _ = payload // suppress compiler warnings when payload isn't used in generated code

        let result = self.init()

        result.configuration = payload.getMap(.configuration)
        result.createdTime = payload.getInt64(.createdTime)
        result.groupId = payload.getString(.groupId)
        result.lastModifiedTime = payload.getInt64(.lastModifiedTime)
        result.operatorId = payload.getString(.operatorId)
        result.tags = payload.getTag(.tags)
        return result
    }

}

public typealias GroupList = [Group]
