// RoleResponse.swift Generated by swagger-codegen  — Custom output templates and post-processing by CodeGeneratorForSoracomSDKSwift.Swaggerer version 0.0d1. Generated 2016-09-12T00:54:57Z

import Foundation


public class RoleResponse: PayloadConvertible {

    public var createDateTime: Int64?
    public var description: String?
    /** Permission\u306EJSON */
    public var permission: String?
    public var roleId: String?
    public var updateDateTime: Int64?

    public required init(
        createDateTime: Int64? = nil, 
        description: String? = nil, 
        permission: String? = nil, 
        roleId: String? = nil, 
        updateDateTime: Int64? = nil
    ) {
        self.createDateTime = createDateTime
        self.description = description
        self.permission = permission
        self.roleId = roleId
        self.updateDateTime = updateDateTime
        
    }

    // MARK: PayloadConvertible

    public func toPayload() -> Payload {

        let payload: Payload = [:]

        payload[.createDateTime] = createDateTime
        payload[.description] = description
        payload[.permission] = permission
        payload[.roleId] = roleId
        payload[.updateDateTime] = updateDateTime

        return payload;
    }

    public static func from(_ payload: Payload?) -> Self? {
        guard let payload = payload else {
            return nil
        }

        _ = payload // suppress compiler warnings when payload isn't used in generated code

        let result = self.init()

        result.createDateTime = payload.decodeInt64(.createDateTime)
        result.description = payload.decodeString(.description)
        result.permission = payload.decodeString(.permission)
        result.roleId = payload.decodeString(.roleId)
        result.updateDateTime = payload.decodeInt64(.updateDateTime)
        return result
    }

}

public typealias RoleResponseList = [RoleResponse]
