// RuleConfigProperty.swift Generated by swagger-codegen ___SORACOM_SDK_SWIFT_SWAGGERER_CODE_GENERATION_METADATA___

import Foundation


public class RuleConfigProperty: PayloadConvertible {

    public enum InactiveTimeoutDateConst: String { 
        case Immediately = "IMMEDIATELY"
        case BeginningOfNextMonth = "BEGINNING_OF_NEXT_MONTH"
        case BeginningOfNextDay = "BEGINNING_OF_NEXT_DAY"
        case AfterOneDay = "AFTER_ONE_DAY"
        case Never = "NEVER"
    }
    public enum TargetStatus: String { 
        case Ready = "ready"
        case Active = "active"
        case Inactive = "inactive"
        case Suspended = "suspended"
        case Terminated = "terminated"
    }
    public enum TargetSpeedClass: String { 
        case S1.minimum = "s1.minimum"
        case S1.slow = "s1.slow"
        case S1.standard = "s1.standard"
        case S1.fast = "s1.fast"
    }
    public var limitTotalTrafficMegaByte: Int64?

    public var inactiveTimeoutDateConst: InactiveTimeoutDateConst?

    /** SubscriberStatusAttributeRule \u306E\u6642\u306E\u307F\u6709\u52B9 */
    public var targetStatus: TargetStatus?

    /** SubscriberSpeedClassAttributeRule \u306E\u6642\u306E\u307F\u6709\u52B9 */
    public var targetSpeedClass: TargetSpeedClass?

    public required init(
        limitTotalTrafficMegaByte: Int64? = nil, 
        inactiveTimeoutDateConst: /* FIXME enum wtf */InactiveTimeoutDateConst = nil, 
        targetStatus: /* FIXME enum wtf */TargetStatus = nil, 
        targetSpeedClass: /* FIXME enum wtf */TargetSpeedClass = nil
    ) {
        self.limitTotalTrafficMegaByte = limitTotalTrafficMegaByte
        self.inactiveTimeoutDateConst = inactiveTimeoutDateConst
        self.targetStatus = targetStatus
        self.targetSpeedClass = targetSpeedClass
        
    }

    // MARK: PayloadConvertible

    public func toPayload() -> Payload {

        let payload: Payload = [:]

        payload[.limitTotalTrafficMegaByte] = limitTotalTrafficMegaByte
        payload[.inactiveTimeoutDateConst] = inactiveTimeoutDateConst
        payload[.targetStatus] = targetStatus
        payload[.targetSpeedClass] = targetSpeedClass

        return payload;
    }

    public static func from(_ payload: Payload?) -> Self? {
        guard let payload = payload else {
            return nil
        }

        _ = payload // suppress compiler warnings when payload isn't used in generated code

        let result = self.init()

        result.limitTotalTrafficMegaByte = payload.getInt64(.limitTotalTrafficMegaByte)
        // inactiveTimeoutDateConst: WHUT FIXME-ENUM-CASE InactiveTimeoutDateConst
        result.inactiveTimeoutDateConst = payload.getInactiveTimeoutDateConst(.inactiveTimeoutDateConst)
        // targetStatus: WHUT FIXME-ENUM-CASE TargetStatus
        result.targetStatus = payload.getTargetStatus(.targetStatus)
        // targetSpeedClass: WHUT FIXME-ENUM-CASE TargetSpeedClass
        result.targetSpeedClass = payload.getTargetSpeedClass(.targetSpeedClass)
        return result
    }

}

public typealias RuleConfigPropertyList = [RuleConfigProperty]
