//
// Generated by SwagGen
// https://github.com/yonaskolb/SwagGen
//

import Foundation

extension Request {

    public class func _deleteVirtualPrivateGatewayIpAddressMapEntry(
        
        vpgId: String,
        key: String,
        responseHandler: ResponseHandler<IpAddressMapEntry>? = nil
    ) ->   Request<IpAddressMapEntry> {

        let path = "/virtual_private_gateways/{vpg_id}/ip_address_map/{key}".replacingOccurrences(of: "{" + "vpgId" + "}", with: "\(vpgId)").replacingOccurrences(of: "{" + "key" + "}", with: "\(key)") // This nonsense should be fixed in the code generator, we might do a PR for at some point...

        let requestObject = Request<IpAddressMapEntry>.init(path, responseHandler: responseHandler)

        
        requestObject.expectedHTTPStatus = 204
        requestObject.method = .delete


        return requestObject
    }

}
