//
// Generated by SwagGen
// https://github.com/yonaskolb/SwagGen
//

import Foundation

extension Request {

    public class func _setRedirectionConfiguration(
        redirectionConfiguration: JunctionRedirectionConfiguration, 
        vpgId: String,
        responseHandler: ResponseHandler<NoResponseBody>? = nil
    ) ->   Request<NoResponseBody> {

        let path = "/virtual_private_gateways/{vpg_id}/junction/set_redirection".replacingOccurrences(of: "{" + "vpgId" + "}", with: "\(vpgId)") // This nonsense should be fixed in the code generator, we might do a PR for at some point...

        let requestObject = Request<NoResponseBody>.init(path, responseHandler: responseHandler)

        requestObject.messageBody = redirectionConfiguration.toData()
        requestObject.expectedHTTPStatus = 200
        requestObject.method = .post


        return requestObject
    }

}
