//
// Generated by SwagGen
// https://github.com/yonaskolb/SwagGen
//

import Foundation

extension Request {

    public class func _getRole(
        
        operatorId: String,
        roleId: String,
        responseHandler: ResponseHandler<RoleResponse>? = nil
    ) ->   Request<RoleResponse> {

        let path  = "/operators/\(operatorId)/roles/\(roleId)"

        let requestObject = Request<RoleResponse>.init(path, responseHandler: responseHandler)

        
        requestObject.expectedHTTPStatus = 200
        requestObject.method = .get


        return requestObject
    }

}
