//
// Generated by SwagGen
// https://github.com/yonaskolb/SwagGen
//

import Foundation

extension Request {

    /**
        Create a SORACOM Lagoon user

        Create a SORACOM Lagoon user.

        Docs: https://dev.soracom.io/en/docs/api/#!/Lagoon/createLagoonUser
    */
    public class func _createLagoonUser(
        request: LagoonUserCreationRequest, 
        responseHandler: ResponseHandler<LagoonUserCreationResponse>? = nil
    ) ->   Request<LagoonUserCreationResponse> {

        let path  = "/lagoon/users"

        let requestObject = Request<LagoonUserCreationResponse>.init(path, responseHandler: responseHandler)

        requestObject.messageBody = request.toData()
        requestObject.expectedHTTPStatus = 201
        requestObject.method = .post


        return requestObject
    }

}
