//
// Generated by SwagGen
// https://github.com/yonaskolb/SwagGen
//

import Foundation

extension Request {

    public class func _registerLagoon(
        request: LagoonRegistrationRequest, 
        responseHandler: ResponseHandler<LagoonRegistrationResponse>? = nil
    ) ->   Request<LagoonRegistrationResponse> {

        let path  = "/lagoon/register"

        let requestObject = Request<LagoonRegistrationResponse>.init(path, responseHandler: responseHandler)

        requestObject.messageBody = request.toData()
        requestObject.expectedHTTPStatus = 201
        requestObject.method = .post


        return requestObject
    }

}
