//
// AttachRoleRequest.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



open class AttachRoleRequest: Codable {

    public var roleId: String?


    
    public init(roleId: String?) {
        self.roleId = roleId
    }
    

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {

        var container = encoder.container(keyedBy: String.self)

        try container.encodeIfPresent(roleId, forKey: "roleId")
    }

    // Decodable protocol methods

    public required init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: String.self)

        roleId = try container.decodeIfPresent(String.self, forKey: "roleId")
    }
}

