//
// CreateVpcPeeringConnectionRequest.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



open class CreateVpcPeeringConnectionRequest: Codable {

    public var peerOwnerId: String?
    public var peerVpcId: String?
    public var destinationCidrBlock: String?
    public var peerRegion: String?


    
    public init(peerOwnerId: String?, peerVpcId: String?, destinationCidrBlock: String?, peerRegion: String?) {
        self.peerOwnerId = peerOwnerId
        self.peerVpcId = peerVpcId
        self.destinationCidrBlock = destinationCidrBlock
        self.peerRegion = peerRegion
    }
    

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {

        var container = encoder.container(keyedBy: String.self)

        try container.encodeIfPresent(peerOwnerId, forKey: "peerOwnerId")
        try container.encodeIfPresent(peerVpcId, forKey: "peerVpcId")
        try container.encodeIfPresent(destinationCidrBlock, forKey: "destinationCidrBlock")
        try container.encodeIfPresent(peerRegion, forKey: "peerRegion")
    }

    // Decodable protocol methods

    public required init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: String.self)

        peerOwnerId = try container.decodeIfPresent(String.self, forKey: "peerOwnerId")
        peerVpcId = try container.decodeIfPresent(String.self, forKey: "peerVpcId")
        destinationCidrBlock = try container.decodeIfPresent(String.self, forKey: "destinationCidrBlock")
        peerRegion = try container.decodeIfPresent(String.self, forKey: "peerRegion")
    }
}

