//
// CreditCard.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



open class CreditCard: Codable {

    public var cvc: String?
    public var expireMonth: Int?
    public var expireYear: Int?
    public var name: String?
    public var number: String?


    
    public init(cvc: String?, expireMonth: Int?, expireYear: Int?, name: String?, number: String?) {
        self.cvc = cvc
        self.expireMonth = expireMonth
        self.expireYear = expireYear
        self.name = name
        self.number = number
    }
    

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {

        var container = encoder.container(keyedBy: String.self)

        try container.encodeIfPresent(cvc, forKey: "cvc")
        try container.encodeIfPresent(expireMonth, forKey: "expireMonth")
        try container.encodeIfPresent(expireYear, forKey: "expireYear")
        try container.encodeIfPresent(name, forKey: "name")
        try container.encodeIfPresent(number, forKey: "number")
    }

    // Decodable protocol methods

    public required init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: String.self)

        cvc = try container.decodeIfPresent(String.self, forKey: "cvc")
        expireMonth = try container.decodeIfPresent(Int.self, forKey: "expireMonth")
        expireYear = try container.decodeIfPresent(Int.self, forKey: "expireYear")
        name = try container.decodeIfPresent(String.self, forKey: "name")
        number = try container.decodeIfPresent(String.self, forKey: "number")
    }
}

