//
// ExpiryTime.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



open class ExpiryTime: Codable {

    public enum ExpiryAction: String, Codable { 
        case donothing = "doNothing"
        case deletesession = "deleteSession"
        case deactivate = "deactivate"
        case suspend = "suspend"
        case terminate = "terminate"
    }
    public var expiryTime: Int64
    public var expiryAction: ExpiryAction?


    
    public init(expiryTime: Int64, expiryAction: ExpiryAction?) {
        self.expiryTime = expiryTime
        self.expiryAction = expiryAction
    }
    

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {

        var container = encoder.container(keyedBy: String.self)

        try container.encode(expiryTime, forKey: "expiryTime")
        try container.encodeIfPresent(expiryAction, forKey: "expiryAction")
    }

    // Decodable protocol methods

    public required init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: String.self)

        expiryTime = try container.decode(Int64.self, forKey: "expiryTime")
        expiryAction = try container.decodeIfPresent(ExpiryAction.self, forKey: "expiryAction")
    }
}

