//
// GenerateUserAuthKeyResponse.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



open class GenerateUserAuthKeyResponse: Codable {

    public var authKey: String?
    public var authKeyId: String?


    
    public init(authKey: String?, authKeyId: String?) {
        self.authKey = authKey
        self.authKeyId = authKeyId
    }
    

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {

        var container = encoder.container(keyedBy: String.self)

        try container.encodeIfPresent(authKey, forKey: "authKey")
        try container.encodeIfPresent(authKeyId, forKey: "authKeyId")
    }

    // Decodable protocol methods

    public required init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: String.self)

        authKey = try container.decodeIfPresent(String.self, forKey: "authKey")
        authKeyId = try container.decodeIfPresent(String.self, forKey: "authKeyId")
    }
}

