//
// GenerateTokenRequest.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



open class GenerateTokenRequest: Codable {

    /** 新しい API トークンの有効期限の長さ（秒単位）。 指定しなければデフォルトは 86400 [秒]（24時間）。 最大値は 172800 [秒]（48時間）。  */
    public var tokenTimeoutSeconds: Int?


    
    public init(tokenTimeoutSeconds: Int?) {
        self.tokenTimeoutSeconds = tokenTimeoutSeconds
    }
    

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {

        var container = encoder.container(keyedBy: String.self)

        try container.encodeIfPresent(tokenTimeoutSeconds, forKey: "tokenTimeoutSeconds")
    }

    // Decodable protocol methods

    public required init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: String.self)

        tokenTimeoutSeconds = try container.decodeIfPresent(Int.self, forKey: "tokenTimeoutSeconds")
    }
}

