//
// GetOperatorResponse.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



open class GetOperatorResponse: Codable {

    public var createDate: String
    public var description: String
    public var email: String
    public var operatorId: String
    public var rootOperatorId: String
    public var updateDate: String


    
    public init(createDate: String, description: String, email: String, operatorId: String, rootOperatorId: String, updateDate: String) {
        self.createDate = createDate
        self.description = description
        self.email = email
        self.operatorId = operatorId
        self.rootOperatorId = rootOperatorId
        self.updateDate = updateDate
    }
    

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {

        var container = encoder.container(keyedBy: String.self)

        try container.encode(createDate, forKey: "createDate")
        try container.encode(description, forKey: "description")
        try container.encode(email, forKey: "email")
        try container.encode(operatorId, forKey: "operatorId")
        try container.encode(rootOperatorId, forKey: "rootOperatorId")
        try container.encode(updateDate, forKey: "updateDate")
    }

    // Decodable protocol methods

    public required init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: String.self)

        createDate = try container.decode(String.self, forKey: "createDate")
        description = try container.decode(String.self, forKey: "description")
        email = try container.decode(String.self, forKey: "email")
        operatorId = try container.decode(String.self, forKey: "operatorId")
        rootOperatorId = try container.decode(String.self, forKey: "rootOperatorId")
        updateDate = try container.decode(String.self, forKey: "updateDate")
    }
}

