//
// LagoonRegistrationResponse.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



open class LagoonRegistrationResponse: Codable {

    /** This email address is used on login with the initial user. */
    public var lagoonUserEmail: String?


    
    public init(lagoonUserEmail: String?) {
        self.lagoonUserEmail = lagoonUserEmail
    }
    

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {

        var container = encoder.container(keyedBy: String.self)

        try container.encodeIfPresent(lagoonUserEmail, forKey: "lagoonUserEmail")
    }

    // Decodable protocol methods

    public required init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: String.self)

        lagoonUserEmail = try container.decodeIfPresent(String.self, forKey: "lagoonUserEmail")
    }
}

