//
// ListOrderedSubscriberResponse.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



open class ListOrderedSubscriberResponse: Codable {

    /** 発注したSIMのリスト */
    public var orderedSubscriberList: [OrderedSubscriber]?


    
    public init(orderedSubscriberList: [OrderedSubscriber]?) {
        self.orderedSubscriberList = orderedSubscriberList
    }
    

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {

        var container = encoder.container(keyedBy: String.self)

        try container.encodeIfPresent(orderedSubscriberList, forKey: "orderedSubscriberList")
    }

    // Decodable protocol methods

    public required init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: String.self)

        orderedSubscriberList = try container.decodeIfPresent([OrderedSubscriber].self, forKey: "orderedSubscriberList")
    }
}

