//
// RegisterGatePeerRequest.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



open class RegisterGatePeerRequest: Codable {

    public var outerIpAddress: String
    public var innerIpAddress: String?


    
    public init(outerIpAddress: String, innerIpAddress: String?) {
        self.outerIpAddress = outerIpAddress
        self.innerIpAddress = innerIpAddress
    }
    

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {

        var container = encoder.container(keyedBy: String.self)

        try container.encode(outerIpAddress, forKey: "outerIpAddress")
        try container.encodeIfPresent(innerIpAddress, forKey: "innerIpAddress")
    }

    // Decodable protocol methods

    public required init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: String.self)

        outerIpAddress = try container.decode(String.self, forKey: "outerIpAddress")
        innerIpAddress = try container.decodeIfPresent(String.self, forKey: "innerIpAddress")
    }
}

