//
// SmsForwardingReport.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



open class SmsForwardingReport: Codable {

    public var messageId: String?


    
    public init(messageId: String?) {
        self.messageId = messageId
    }
    

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {

        var container = encoder.container(keyedBy: String.self)

        try container.encodeIfPresent(messageId, forKey: "messageId")
    }

    // Decodable protocol methods

    public required init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: String.self)

        messageId = try container.decodeIfPresent(String.self, forKey: "messageId")
    }
}

