//
// Generated by SwagGen
// https://github.com/yonaskolb/SwagGen
//

import Foundation

extension Request {

    public class func _listDataSourceResources(
        
        resourceType: ResourceType? = nil,
        limit: Int? = nil,
        lastEvaluatedKey: String? = nil,
        responseHandler: ResponseHandler<[DataSourceResourceMetadata]>? = nil
    ) ->   Request<[DataSourceResourceMetadata]> {

        let path  = "/data/resources"

        let requestObject = Request<[DataSourceResourceMetadata]>.init(path, responseHandler: responseHandler)

        
        requestObject.expectedHTTPStatus = 200
        requestObject.method = .get

        requestObject.query = makeQueryDictionary([
            "resourceType": resourceType,
            "limit": limit,
            "lastEvaluatedKey": lastEvaluatedKey
        ])

        return requestObject
    }

}
