//
// Generated by SwagGen
// https://github.com/yonaskolb/SwagGen
//

import Foundation

extension Request where T == SigfoxDevice {

    /**
        Bulk Insert or Update Sigfox device Tags.

        Inserts/updates tags for the specified Sigfox device.

        Docs: https://dev.soracom.io/en/docs/api/#!/SigfoxDevice/putSigfoxDeviceTags
    */
    public class func putSigfoxDeviceTags(
        tags: [TagUpdateRequest], 
        deviceId: String,
        responseHandler: ResponseHandler<SigfoxDevice>? = nil
    ) ->   Request<SigfoxDevice> {

        let path  = "/sigfox_devices/\(deviceId)/tags"

        let requestObject = Request<SigfoxDevice>.init(path, responseHandler: responseHandler)

        requestObject.messageBody = tags.toData()
        requestObject.expectedHTTPStatus = 200
        requestObject.method = .put


        return requestObject
    }

}
