//
// Generated by SwagGen
// https://github.com/yonaskolb/SwagGen
//

import Foundation

extension Request {

    /**
        Delete LoRa network set tag.

        Deletes a tag from the specified LoRa network set.

        Docs: https://dev.soracom.io/en/docs/api/#!/LoraNetworkSet/deleteLoraNetworkSetTag
    */
    public class func _deleteLoraNetworkSetTag(
        
        nsId: String,
        tagName: String,
        responseHandler: ResponseHandler<NoResponseBody>? = nil
    ) ->   Request<NoResponseBody> {

        let path  = "/lora_network_sets/\(nsId)/tags/\(tagName)"

        let requestObject = Request<NoResponseBody>.init(path, responseHandler: responseHandler)

        
        requestObject.expectedHTTPStatus = 204
        requestObject.method = .delete


        return requestObject
    }

}
