//
// Generated by SwagGen
// https://github.com/yonaskolb/SwagGen
//

import Foundation

extension Request {

    public class func _listProducts(
        
        responseHandler: ResponseHandler<ListProductResponse>? = nil
    ) ->   Request<ListProductResponse> {

        let path = "/products" // This nonsense should be fixed in the code generator, we might do a PR for at some point...

        let requestObject = Request<ListProductResponse>.init(path, responseHandler: responseHandler)

        
        requestObject.expectedHTTPStatus = 200
        requestObject.method = .get


        return requestObject
    }

}
