//
// APICallError.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


public class APICallError: JSONEncodable {
    public var errorMessage: APICallErrorMessage?
    public var httpStatus: Int?

    public init() {}

    // MARK: JSONEncodable
    func encodeToJSON() -> AnyObject {
        var nillableDictionary = [String:AnyObject?]()
        nillableDictionary["errorMessage"] = self.errorMessage?.encodeToJSON()
        nillableDictionary["httpStatus"] = self.httpStatus?.encodeToJSON()
        let dictionary: [String:AnyObject] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}
