//
// AuthRequest.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


public class AuthRequest: JSONEncodable {
    public var authKey: String?
    public var authKeyId: String?
    public var email: String?
    public var operatorId: String?
    public var password: String?
    public var tokenTimeoutSeconds: Int?
    public var userName: String?

    public init() {}

    // MARK: JSONEncodable
    func encodeToJSON() -> AnyObject {
        var nillableDictionary = [String:AnyObject?]()
        nillableDictionary["authKey"] = self.authKey
        nillableDictionary["authKeyId"] = self.authKeyId
        nillableDictionary["email"] = self.email
        nillableDictionary["operatorId"] = self.operatorId
        nillableDictionary["password"] = self.password
        nillableDictionary["tokenTimeoutSeconds"] = self.tokenTimeoutSeconds?.encodeToJSON()
        nillableDictionary["userName"] = self.userName
        let dictionary: [String:AnyObject] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}
