//
// DataTrafficStats.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


public class DataTrafficStats: JSONEncodable {
    public var downloadByteSizeTotal: Int?
    public var downloadPacketSizeTotal: Int?
    public var uploadByteSizeTotal: Int?
    public var uploadPacketSizeTotal: Int?

    public init() {}

    // MARK: JSONEncodable
    func encodeToJSON() -> AnyObject {
        var nillableDictionary = [String:AnyObject?]()
        nillableDictionary["downloadByteSizeTotal"] = self.downloadByteSizeTotal?.encodeToJSON()
        nillableDictionary["downloadPacketSizeTotal"] = self.downloadPacketSizeTotal?.encodeToJSON()
        nillableDictionary["uploadByteSizeTotal"] = self.uploadByteSizeTotal?.encodeToJSON()
        nillableDictionary["uploadPacketSizeTotal"] = self.uploadPacketSizeTotal?.encodeToJSON()
        let dictionary: [String:AnyObject] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}
