//
// ExpiryTime.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


public class ExpiryTime: JSONEncodable {
    public enum ExpiryAction: String { 
        case Donothing = "doNothing"
        case Deletesession = "deleteSession"
        case Deactivate = "deactivate"
        case Terminate = "terminate"
    }
    public var expiryTime: Int?
    public var expiryAction: ExpiryAction?

    public init() {}

    // MARK: JSONEncodable
    func encodeToJSON() -> AnyObject {
        var nillableDictionary = [String:AnyObject?]()
        nillableDictionary["expiryTime"] = self.expiryTime?.encodeToJSON()
        nillableDictionary["expiryAction"] = self.expiryAction?.rawValue
        let dictionary: [String:AnyObject] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}
