//
// GatePeer.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


public class GatePeer: JSONEncodable {
    public var outerIpAddress: String?
    public var innerIpAddress: String?
    public var ownedByCustomer: Bool?

    public init() {}

    // MARK: JSONEncodable
    func encodeToJSON() -> AnyObject {
        var nillableDictionary = [String:AnyObject?]()
        nillableDictionary["outerIpAddress"] = self.outerIpAddress
        nillableDictionary["innerIpAddress"] = self.innerIpAddress
        nillableDictionary["ownedByCustomer"] = self.ownedByCustomer
        let dictionary: [String:AnyObject] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}
