//
// GetOrderResponse.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


public class GetOrderResponse: JSONEncodable {
    public enum OrderStatus: String { 
        case Ordering = "ordering"
        case Ordered = "ordered"
        case Kitting = "kitting"
        case Shipped = "shipped"
        case Received = "received"
        case Cancelling = "cancelling"
        case Cancelled = "cancelled"
        case Failed = "failed"
    }
    /** \u30E1\u30FC\u30EB\u30A2\u30C9\u30EC\u30B9 */
    public var email: String?
    /** \u767A\u6CE8\u65E5\u6642 */
    public var orderDateTime: String?
    /** \u767A\u6CE8ID */
    public var orderId: String?
    /** \u767A\u6CE8\u5546\u54C1\u30EA\u30B9\u30C8 */
    public var orderItemList: [EstimatedOrderItemModel]?
    /** \u767A\u6CE8\u30B9\u30C6\u30FC\u30BF\u30B9 */
    public var orderStatus: OrderStatus?
    /** \u767A\u9001\u5148 */
    public var shippingAddress: ShippingAddressModel?
    /** \u5546\u54C1\u767A\u9001\u5148ID */
    public var shippingAddressId: String?
    /** \u914D\u9001\u6599 */
    public var shippingCost: Double?
    /** \u5B85\u914D\u4FBF\u9001\u308A\u72B6\u756A\u53F7 */
    public var shippingLabelNumber: String?
    /** \u6D88\u8CBB\u7A0E */
    public var taxAmount: Double?
    /** \u5408\u8A08\u91D1\u984D */
    public var totalAmount: Double?

    public init() {}

    // MARK: JSONEncodable
    func encodeToJSON() -> AnyObject {
        var nillableDictionary = [String:AnyObject?]()
        nillableDictionary["email"] = self.email
        nillableDictionary["orderDateTime"] = self.orderDateTime
        nillableDictionary["orderId"] = self.orderId
        nillableDictionary["orderItemList"] = self.orderItemList?.encodeToJSON()
        nillableDictionary["orderStatus"] = self.orderStatus?.rawValue
        nillableDictionary["shippingAddress"] = self.shippingAddress?.encodeToJSON()
        nillableDictionary["shippingAddressId"] = self.shippingAddressId
        nillableDictionary["shippingCost"] = self.shippingCost
        nillableDictionary["shippingLabelNumber"] = self.shippingLabelNumber
        nillableDictionary["taxAmount"] = self.taxAmount
        nillableDictionary["totalAmount"] = self.totalAmount
        let dictionary: [String:AnyObject] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}
