//
// Group.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


public class Group: JSONEncodable {
    public var configuration: Map?
    public var createdTime: Int?
    public var groupId: String?
    public var lastModifiedTime: Int?
    public var operatorId: String?
    public var tags: Tag?

    public init() {}

    // MARK: JSONEncodable
    func encodeToJSON() -> AnyObject {
        var nillableDictionary = [String:AnyObject?]()
        nillableDictionary["configuration"] = self.configuration?.encodeToJSON()
        nillableDictionary["createdTime"] = self.createdTime?.encodeToJSON()
        nillableDictionary["groupId"] = self.groupId
        nillableDictionary["lastModifiedTime"] = self.lastModifiedTime?.encodeToJSON()
        nillableDictionary["operatorId"] = self.operatorId
        nillableDictionary["tags"] = self.tags?.encodeToJSON()
        let dictionary: [String:AnyObject] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}
