//
// IpAddressMapEntry.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


public class IpAddressMapEntry: JSONEncodable {
    public enum _type: String { 
        case Static = "static"
        case Dynamic = "dynamic"
        case Customergatepeer = "customerGatePeer"
        case Gatepeer = "gatePeer"
    }
    public var key: String?
    public var ipAddress: String?
    public var _type: _type?

    public init() {}

    // MARK: JSONEncodable
    func encodeToJSON() -> AnyObject {
        var nillableDictionary = [String:AnyObject?]()
        nillableDictionary["key"] = self.key
        nillableDictionary["ipAddress"] = self.ipAddress
        nillableDictionary["type"] = self._type?.rawValue
        let dictionary: [String:AnyObject] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}
