//
// Subscriber.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


public class Subscriber: JSONEncodable {
    public var imsi: String?
    public var msisdn: String?
    public var serialNumber: String?
    public var iccid: String?
    public var apn: String?
    public var speedClass: String?
    public var createdAt: Int?
    public var lastModifiedAt: Int?
    public var expiryTime: Int?
    public var expiryAction: String?
    public var status: String?
    public var sessionStatus: SessionStatus?
    public var tags: Map?
    public var operatorId: String?

    public init() {}

    // MARK: JSONEncodable
    func encodeToJSON() -> AnyObject {
        var nillableDictionary = [String:AnyObject?]()
        nillableDictionary["imsi"] = self.imsi
        nillableDictionary["msisdn"] = self.msisdn
        nillableDictionary["serialNumber"] = self.serialNumber
        nillableDictionary["iccid"] = self.iccid
        nillableDictionary["apn"] = self.apn
        nillableDictionary["speedClass"] = self.speedClass
        nillableDictionary["createdAt"] = self.createdAt?.encodeToJSON()
        nillableDictionary["lastModifiedAt"] = self.lastModifiedAt?.encodeToJSON()
        nillableDictionary["expiryTime"] = self.expiryTime?.encodeToJSON()
        nillableDictionary["expiryAction"] = self.expiryAction
        nillableDictionary["status"] = self.status
        nillableDictionary["sessionStatus"] = self.sessionStatus?.encodeToJSON()
        nillableDictionary["tags"] = self.tags?.encodeToJSON()
        nillableDictionary["operatorId"] = self.operatorId
        let dictionary: [String:AnyObject] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}
