//
// Generated by SwagGen
// https://github.com/yonaskolb/SwagGen
//

import Foundation

extension Request {

    /**
        Disable Termination of Sigfox device.

        Disables termination of specified Sigfox device.

        Docs: https://dev.soracom.io/en/docs/api/#!/SigfoxDevice/disableTerminationOnSigfoxDevice
    */
    public class func _disableTerminationOnSigfoxDevice(
        
        deviceId: String,
        responseHandler: ResponseHandler<SigfoxDevice>? = nil
    ) ->   Request<SigfoxDevice> {

        let path  = "/sigfox_devices/\(deviceId)/disable_termination"

        let requestObject = Request<SigfoxDevice>.init(path, responseHandler: responseHandler)

        
        requestObject.expectedHTTPStatus = 200
        requestObject.method = .post


        return requestObject
    }

}
