//
// Generated by SwagGen
// https://github.com/yonaskolb/SwagGen
//

import Foundation

extension Request {

    public class func _registerSigfoxDevice(
        registrationRequest: SigfoxRegistrationRequest, 
        deviceId: String,
        responseHandler: ResponseHandler<SigfoxDevice>? = nil
    ) ->   Request<SigfoxDevice> {

        let path  = "/sigfox_devices/\(deviceId)/register"

        let requestObject = Request<SigfoxDevice>.init(path, responseHandler: responseHandler)

        requestObject.messageBody = registrationRequest.toData()
        requestObject.expectedHTTPStatus = 200
        requestObject.method = .post


        return requestObject
    }

}
