//
// Generated by SwagGen
// https://github.com/yonaskolb/SwagGen
//

import Foundation

extension Request where T == LoraDevice {

    /**
        Get LoRa device.

        Returns information about the specified LoRa device.

        Docs: https://dev.soracom.io/en/docs/api/#!/LoraDevice/getLoraDevice
    */
    public class func getLoraDevice(
        
        deviceId: String,
        responseHandler: ResponseHandler<LoraDevice>? = nil
    ) ->   Request<LoraDevice> {

        let path  = "/lora_devices/\(deviceId)"

        let requestObject = Request<LoraDevice>.init(path, responseHandler: responseHandler)

        
        requestObject.expectedHTTPStatus = 200
        requestObject.method = .get


        return requestObject
    }

}
