//
// Generated by SwagGen
// https://github.com/yonaskolb/SwagGen
//

import Foundation

extension Request where T == NoResponseBody {

    /**
        Delete Operator AuthKey.

        Deletes an AuthKey from the operator.

        Docs: https://dev.soracom.io/en/docs/api/#!/Operator/deleteOperatorAuthKey
    */
    public class func deleteOperatorAuthKey(
        
        operatorId: String,
        authKeyId: String,
        responseHandler: ResponseHandler<NoResponseBody>? = nil
    ) ->   Request<NoResponseBody> {

        let path  = "/operators/\(operatorId)/auth_keys/\(authKeyId)"

        let requestObject = Request<NoResponseBody>.init(path, responseHandler: responseHandler)

        
        requestObject.expectedHTTPStatus = 200
        requestObject.method = .delete


        return requestObject
    }

}
