//
// Generated by SwagGen
// https://github.com/yonaskolb/SwagGen
//

import Foundation

extension Request where T == NoResponseBody {

    /**
        Update password of a SORACOM Lagoon user

        Update password of a SORACOM Lagoon user.

        [API Documentation](https://dev.soracom.io/en/docs/api/#!/Lagoon/updateLagoonUserPassword)
    */
    public class func updateLagoonUserPassword(
        request: LagoonUserPasswordUpdatingRequest, 
        lagoonUserId: Int,
        responseHandler: ResponseHandler<NoResponseBody>? = nil
    ) ->   Request<NoResponseBody> {

        let path  = "/lagoon/users/\(lagoonUserId)/password"

        let requestObject = Request<NoResponseBody>.init(path, responseHandler: responseHandler)

        requestObject.messageBody = request.toData()
        requestObject.expectedHTTPStatus = 200
        requestObject.method = .put


        return requestObject
    }

}
