//
// Generated by SwagGen
// https://github.com/yonaskolb/SwagGen
//

import Foundation

extension Request where T == LoraGateway {

    /**
        Terminate LoRa gateway.

        Terminates the specified LoRa gateway

        [API Documentation](https://dev.soracom.io/en/docs/api/#!/LoraGateway/terminateLoraGateway)
    */
    public class func terminateLoraGateway(
        
        gatewayId: String,
        responseHandler: ResponseHandler<LoraGateway>? = nil
    ) ->   Request<LoraGateway> {

        let path  = "/lora_gateways/\(gatewayId)/terminate"

        let requestObject = Request<LoraGateway>.init(path, responseHandler: responseHandler)

        
        requestObject.expectedHTTPStatus = 200
        requestObject.method = .post


        return requestObject
    }

}
