//
// Generated by SwagGen
// https://github.com/yonaskolb/SwagGen
//

import Foundation

extension Request where T == LoraGateway {

    /**
        Unset Network Set ID of LoRa gateway.

        Unset network set ID of the specified LoRa gateway.

        Docs: https://dev.soracom.io/en/docs/api/#!/LoraGateway/unsetLoraNetworkSet
    */
    public class func unsetLoraNetworkSet(
        
        gatewayId: String,
        responseHandler: ResponseHandler<LoraGateway>? = nil
    ) ->   Request<LoraGateway> {

        let path  = "/lora_gateways/\(gatewayId)/unset_network_set"

        let requestObject = Request<LoraGateway>.init(path, responseHandler: responseHandler)

        
        requestObject.expectedHTTPStatus = 200
        requestObject.method = .post


        return requestObject
    }

}
