//
// Generated by SwagGen
// https://github.com/yonaskolb/SwagGen
//

import Foundation

extension Request where T == EventHandlerModel {

    /**
        Create Event Handler.

        Creates a new event handler. Please see also https://dev.soracom.io/en/docs/event_handler/

        [API Documentation](https://dev.soracom.io/en/docs/api/#!/EventHandler/createEventHandler)
    */
    public class func createEventHandler(
        req: CreateEventHandlerRequest, 
        responseHandler: ResponseHandler<EventHandlerModel>? = nil
    ) ->   Request<EventHandlerModel> {

        let path  = "/event_handlers"

        let requestObject = Request<EventHandlerModel>.init(path, responseHandler: responseHandler)

        requestObject.messageBody = req.toData()
        requestObject.expectedHTTPStatus = 201
        requestObject.method = .post


        return requestObject
    }

}
