//
// Generated by SwagGen
// https://github.com/yonaskolb/SwagGen
//

import Foundation

extension Request where T == [EventHandlerModel] {

    /**
        List Event Handlers.

        Returns a list of event handlers.

        [API Documentation](https://dev.soracom.io/en/docs/api/#!/EventHandler/listEventHandlers)
    */
    public class func listEventHandlers(
        
        target: Target? = nil,
        responseHandler: ResponseHandler<[EventHandlerModel]>? = nil
    ) ->   Request<[EventHandlerModel]> {

        let path  = "/event_handlers"

        let requestObject = Request<[EventHandlerModel]>.init(path, responseHandler: responseHandler)

        
        requestObject.expectedHTTPStatus = 200
        requestObject.method = .get

        requestObject.query = makeQueryDictionary([
            "target": target
        ])

        return requestObject
    }

}
