//
// Generated by SwagGen
// https://github.com/yonaskolb/SwagGen
//

import Foundation

extension Request where T == NoResponseBody {

    /**
        Gets a data entry

        Gets a data entry identified with resource ID and timestamp

        [API Documentation](https://dev.soracom.io/en/docs/api/#!/DataEntry/getDataEntry)
    */
    public class func getDataEntry(
        
        resourceType: ResourceType,
        resourceId: String,
        time: Int,
        responseHandler: ResponseHandler<NoResponseBody>? = nil
    ) ->   Request<NoResponseBody> {

        let path  = "/data/\(resourceType.encode())/\(resourceId)/{time}"

        let requestObject = Request<NoResponseBody>.init(path, responseHandler: responseHandler)

        
        requestObject.expectedHTTPStatus = 200
        requestObject.method = .get

        requestObject.query = makeQueryDictionary([
            "time": time
        ])

        return requestObject
    }

}
