//
// OperatorAPI.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Alamofire



public class OperatorAPI: APIBase {
    
    
    
    /**
     
     Create Operator.
     
     - parameter request: (body) request 
     - parameter completion: completion handler to receive the data and the error objects
     */
    public class func createOperator(request request: RegisterOperatorsRequest, completion: ((error: ErrorType?) -> Void)) {
        createOperatorWithRequestBuilder(request: request).execute { (response, error) -> Void in
            completion(error: error);
        }
    }


    /**
     
     Create Operator.
     
     - POST /operators
     - Makes a request to create a new operator. An e-mail is sent to the e-mail address specified in the parameters, containing a one-time token for verifying the operator\u2019s registration.
     - API Key:
       - type: apiKey X-Soracom-API-Key 
       - name: api_key
     - API Key:
       - type: apiKey X-Soracom-Token 
       - name: api_token
     
     - parameter request: (body) request 

     - returns: RequestBuilder<Void> 
     */
    public class func createOperatorWithRequestBuilder(request request: RegisterOperatorsRequest) -> RequestBuilder<Void> {
        let path = "/operators"
        let URLString = SwaggerClientAPI.basePath + path
        
        let parameters = request.encodeToJSON() as? [String:AnyObject]
 
        let convertedParameters = APIHelper.convertBoolToString(parameters)
 
        let requestBuilder: RequestBuilder<Void>.Type = SwaggerClientAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "POST", URLString: URLString, parameters: convertedParameters, isBody: true)
    }

    
    
    
    
    
    /**
     
     Delete Operator AuthKey.
     
     - parameter operatorId: (path) operator_id 
     - parameter authKeyId: (path) auth_key_id 
     - parameter completion: completion handler to receive the data and the error objects
     */
    public class func deleteOperatorAuthKey(operatorId operatorId: String, authKeyId: String, completion: ((error: ErrorType?) -> Void)) {
        deleteOperatorAuthKeyWithRequestBuilder(operatorId: operatorId, authKeyId: authKeyId).execute { (response, error) -> Void in
            completion(error: error);
        }
    }


    /**
     
     Delete Operator AuthKey.
     
     - DELETE /operators/{operatorId}/auth_keys/{authKeyId}
     - Deletes an AuthKey from the operator.
     - API Key:
       - type: apiKey X-Soracom-API-Key 
       - name: api_key
     - API Key:
       - type: apiKey X-Soracom-Token 
       - name: api_token
     
     - parameter operatorId: (path) operator_id 
     - parameter authKeyId: (path) auth_key_id 

     - returns: RequestBuilder<Void> 
     */
    public class func deleteOperatorAuthKeyWithRequestBuilder(operatorId operatorId: String, authKeyId: String) -> RequestBuilder<Void> {
        var path = "/operators/{operatorId}/auth_keys/{authKeyId}"
        path = path.stringByReplacingOccurrencesOfString("{operatorId}", withString: "\(operatorId)", options: .LiteralSearch, range: nil)
        path = path.stringByReplacingOccurrencesOfString("{authKeyId}", withString: "\(authKeyId)", options: .LiteralSearch, range: nil)
        let URLString = SwaggerClientAPI.basePath + path
        
        let nillableParameters: [String:AnyObject?] = [:]
 
        let parameters = APIHelper.rejectNil(nillableParameters)
 
        let convertedParameters = APIHelper.convertBoolToString(parameters)
 
        let requestBuilder: RequestBuilder<Void>.Type = SwaggerClientAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "DELETE", URLString: URLString, parameters: convertedParameters, isBody: true)
    }

    
    
    
    
    
    /**
     
     Generate Authentication Token.
     
     - parameter operatorId: (path) operator ID 
     - parameter request: (body) request 
     - parameter completion: completion handler to receive the data and the error objects
     */
    public class func generateAuthToken(operatorId operatorId: String, request: GenerateTokenRequest, completion: ((data: GenerateTokenResponse?, error: ErrorType?) -> Void)) {
        generateAuthTokenWithRequestBuilder(operatorId: operatorId, request: request).execute { (response, error) -> Void in
            completion(data: response?.body, error: error);
        }
    }


    /**
     
     Generate Authentication Token.
     
     - POST /operators/{operatorId}/token
     - Generates a new API token. If you insert the current API token into the header and make a request, a response is returned containing the new API token. You can then use the new API token in future requests.
     - API Key:
       - type: apiKey X-Soracom-API-Key 
       - name: api_key
     - API Key:
       - type: apiKey X-Soracom-Token 
       - name: api_token
     - examples: [{contentType=application/json, example={
  "token" : "aeiou"
}}]
     
     - parameter operatorId: (path) operator ID 
     - parameter request: (body) request 

     - returns: RequestBuilder<GenerateTokenResponse> 
     */
    public class func generateAuthTokenWithRequestBuilder(operatorId operatorId: String, request: GenerateTokenRequest) -> RequestBuilder<GenerateTokenResponse> {
        var path = "/operators/{operatorId}/token"
        path = path.stringByReplacingOccurrencesOfString("{operatorId}", withString: "\(operatorId)", options: .LiteralSearch, range: nil)
        let URLString = SwaggerClientAPI.basePath + path
        
        let parameters = request.encodeToJSON() as? [String:AnyObject]
 
        let convertedParameters = APIHelper.convertBoolToString(parameters)
 
        let requestBuilder: RequestBuilder<GenerateTokenResponse>.Type = SwaggerClientAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "POST", URLString: URLString, parameters: convertedParameters, isBody: true)
    }

    
    
    
    /**
     
     Generate Operator AuthKey.
     
     - parameter operatorId: (path) operator_id 
     - parameter completion: completion handler to receive the data and the error objects
     */
    public class func generateOperatorAuthKey(operatorId operatorId: String, completion: ((data: GenerateOperatorsAuthKeyResponse?, error: ErrorType?) -> Void)) {
        generateOperatorAuthKeyWithRequestBuilder(operatorId: operatorId).execute { (response, error) -> Void in
            completion(data: response?.body, error: error);
        }
    }


    /**
     
     Generate Operator AuthKey.
     
     - POST /operators/{operatorId}/auth_keys
     - Generates an AuthKey for the operator.
     - API Key:
       - type: apiKey X-Soracom-API-Key 
       - name: api_key
     - API Key:
       - type: apiKey X-Soracom-Token 
       - name: api_token
     - examples: [{contentType=application/json, example={
  "authKey" : "aeiou",
  "authKeyId" : "aeiou"
}}]
     
     - parameter operatorId: (path) operator_id 

     - returns: RequestBuilder<GenerateOperatorsAuthKeyResponse> 
     */
    public class func generateOperatorAuthKeyWithRequestBuilder(operatorId operatorId: String) -> RequestBuilder<GenerateOperatorsAuthKeyResponse> {
        var path = "/operators/{operatorId}/auth_keys"
        path = path.stringByReplacingOccurrencesOfString("{operatorId}", withString: "\(operatorId)", options: .LiteralSearch, range: nil)
        let URLString = SwaggerClientAPI.basePath + path
        
        let nillableParameters: [String:AnyObject?] = [:]
 
        let parameters = APIHelper.rejectNil(nillableParameters)
 
        let convertedParameters = APIHelper.convertBoolToString(parameters)
 
        let requestBuilder: RequestBuilder<GenerateOperatorsAuthKeyResponse>.Type = SwaggerClientAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "POST", URLString: URLString, parameters: convertedParameters, isBody: true)
    }

    
    
    
    /**
     
     Generate Token for Support Console.
     
     - parameter operatorId: (path) operator ID 
     - parameter completion: completion handler to receive the data and the error objects
     */
    public class func generateSupportToken(operatorId operatorId: String, completion: ((data: SupportTokenResponse?, error: ErrorType?) -> Void)) {
        generateSupportTokenWithRequestBuilder(operatorId: operatorId).execute { (response, error) -> Void in
            completion(data: response?.body, error: error);
        }
    }


    /**
     
     Generate Token for Support Console.
     
     - POST /operators/{operatorId}/support/token
     - Returns a token for accessing the support console.
     - API Key:
       - type: apiKey X-Soracom-API-Key 
       - name: api_key
     - API Key:
       - type: apiKey X-Soracom-Token 
       - name: api_token
     - examples: [{contentType=application/json, example={
  "token" : "aeiou"
}}]
     
     - parameter operatorId: (path) operator ID 

     - returns: RequestBuilder<SupportTokenResponse> 
     */
    public class func generateSupportTokenWithRequestBuilder(operatorId operatorId: String) -> RequestBuilder<SupportTokenResponse> {
        var path = "/operators/{operatorId}/support/token"
        path = path.stringByReplacingOccurrencesOfString("{operatorId}", withString: "\(operatorId)", options: .LiteralSearch, range: nil)
        let URLString = SwaggerClientAPI.basePath + path
        
        let nillableParameters: [String:AnyObject?] = [:]
 
        let parameters = APIHelper.rejectNil(nillableParameters)
 
        let convertedParameters = APIHelper.convertBoolToString(parameters)
 
        let requestBuilder: RequestBuilder<SupportTokenResponse>.Type = SwaggerClientAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "POST", URLString: URLString, parameters: convertedParameters, isBody: true)
    }

    
    
    
    /**
     
     Get Operator.
     
     - parameter operatorId: (path) operator ID 
     - parameter completion: completion handler to receive the data and the error objects
     */
    public class func getOperator(operatorId operatorId: String, completion: ((data: GetOperatorResponse?, error: ErrorType?) -> Void)) {
        getOperatorWithRequestBuilder(operatorId: operatorId).execute { (response, error) -> Void in
            completion(data: response?.body, error: error);
        }
    }


    /**
     
     Get Operator.
     
     - GET /operators/{operatorId}
     - Returns information about the operator.
     - API Key:
       - type: apiKey X-Soracom-API-Key 
       - name: api_key
     - API Key:
       - type: apiKey X-Soracom-Token 
       - name: api_token
     - examples: [{contentType=application/json, example={
  "updateDate" : "aeiou",
  "description" : "aeiou",
  "operatorId" : "aeiou",
  "email" : "aeiou",
  "rootOperatorId" : "aeiou",
  "createDate" : "aeiou"
}}]
     
     - parameter operatorId: (path) operator ID 

     - returns: RequestBuilder<GetOperatorResponse> 
     */
    public class func getOperatorWithRequestBuilder(operatorId operatorId: String) -> RequestBuilder<GetOperatorResponse> {
        var path = "/operators/{operatorId}"
        path = path.stringByReplacingOccurrencesOfString("{operatorId}", withString: "\(operatorId)", options: .LiteralSearch, range: nil)
        let URLString = SwaggerClientAPI.basePath + path
        
        let nillableParameters: [String:AnyObject?] = [:]
 
        let parameters = APIHelper.rejectNil(nillableParameters)
 
        let convertedParameters = APIHelper.convertBoolToString(parameters)
 
        let requestBuilder: RequestBuilder<GetOperatorResponse>.Type = SwaggerClientAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "GET", URLString: URLString, parameters: convertedParameters, isBody: true)
    }

    
    
    
    /**
     
     Issue Email Change Token.
     
     - parameter request: (body) request 
     - parameter completion: completion handler to receive the data and the error objects
     */
    public class func issueEmailChangeToken(request request: IssueEmailChangeTokenRequest, completion: ((error: ErrorType?) -> Void)) {
        issueEmailChangeTokenWithRequestBuilder(request: request).execute { (response, error) -> Void in
            completion(error: error);
        }
    }


    /**
     
     Issue Email Change Token.
     
     - POST /operators/email_change_token/issue
     - Sends an e-mail with a one-time token for executing the e-mail address change.
     - API Key:
       - type: apiKey X-Soracom-API-Key 
       - name: api_key
     - API Key:
       - type: apiKey X-Soracom-Token 
       - name: api_token
     
     - parameter request: (body) request 

     - returns: RequestBuilder<Void> 
     */
    public class func issueEmailChangeTokenWithRequestBuilder(request request: IssueEmailChangeTokenRequest) -> RequestBuilder<Void> {
        let path = "/operators/email_change_token/issue"
        let URLString = SwaggerClientAPI.basePath + path
        
        let parameters = request.encodeToJSON() as? [String:AnyObject]
 
        let convertedParameters = APIHelper.convertBoolToString(parameters)
 
        let requestBuilder: RequestBuilder<Void>.Type = SwaggerClientAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "POST", URLString: URLString, parameters: convertedParameters, isBody: true)
    }

    
    
    
    /**
     
     List Operator AuthKeys.
     
     - parameter operatorId: (path) operator_id 
     - parameter completion: completion handler to receive the data and the error objects
     */
    public class func listOperatorAuthKeys(operatorId operatorId: String, completion: ((data: [AuthKeyResponse]?, error: ErrorType?) -> Void)) {
        listOperatorAuthKeysWithRequestBuilder(operatorId: operatorId).execute { (response, error) -> Void in
            completion(data: response?.body, error: error);
        }
    }


    /**
     
     List Operator AuthKeys.
     
     - GET /operators/{operatorId}/auth_keys
     - Returns the operator's AuthKey list.
     - API Key:
       - type: apiKey X-Soracom-API-Key 
       - name: api_key
     - API Key:
       - type: apiKey X-Soracom-Token 
       - name: api_token
     - examples: [{contentType=application/json, example=[ {
  "authKeyId" : "aeiou",
  "lastUsedDateTime" : 123456789,
  "createDateTime" : 123456789
} ]}]
     
     - parameter operatorId: (path) operator_id 

     - returns: RequestBuilder<[AuthKeyResponse]> 
     */
    public class func listOperatorAuthKeysWithRequestBuilder(operatorId operatorId: String) -> RequestBuilder<[AuthKeyResponse]> {
        var path = "/operators/{operatorId}/auth_keys"
        path = path.stringByReplacingOccurrencesOfString("{operatorId}", withString: "\(operatorId)", options: .LiteralSearch, range: nil)
        let URLString = SwaggerClientAPI.basePath + path
        
        let nillableParameters: [String:AnyObject?] = [:]
 
        let parameters = APIHelper.rejectNil(nillableParameters)
 
        let convertedParameters = APIHelper.convertBoolToString(parameters)
 
        let requestBuilder: RequestBuilder<[AuthKeyResponse]>.Type = SwaggerClientAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "GET", URLString: URLString, parameters: convertedParameters, isBody: true)
    }

    
    
    
    
    
    /**
     
     Update Operator Password.
     
     - parameter operatorId: (path) operator ID 
     - parameter request: (body) request 
     - parameter completion: completion handler to receive the data and the error objects
     */
    public class func updateOperatorPassword(operatorId operatorId: String, request: UpdatePasswordRequest, completion: ((error: ErrorType?) -> Void)) {
        updateOperatorPasswordWithRequestBuilder(operatorId: operatorId, request: request).execute { (response, error) -> Void in
            completion(error: error);
        }
    }


    /**
     
     Update Operator Password.
     
     - POST /operators/{operatorId}/password
     - Updates the operator's password.
     - API Key:
       - type: apiKey X-Soracom-API-Key 
       - name: api_key
     - API Key:
       - type: apiKey X-Soracom-Token 
       - name: api_token
     
     - parameter operatorId: (path) operator ID 
     - parameter request: (body) request 

     - returns: RequestBuilder<Void> 
     */
    public class func updateOperatorPasswordWithRequestBuilder(operatorId operatorId: String, request: UpdatePasswordRequest) -> RequestBuilder<Void> {
        var path = "/operators/{operatorId}/password"
        path = path.stringByReplacingOccurrencesOfString("{operatorId}", withString: "\(operatorId)", options: .LiteralSearch, range: nil)
        let URLString = SwaggerClientAPI.basePath + path
        
        let parameters = request.encodeToJSON() as? [String:AnyObject]
 
        let convertedParameters = APIHelper.convertBoolToString(parameters)
 
        let requestBuilder: RequestBuilder<Void>.Type = SwaggerClientAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "POST", URLString: URLString, parameters: convertedParameters, isBody: true)
    }

    
    
    
    /**
     
     Verify Email Change Token.
     
     - parameter request: (body) request 
     - parameter completion: completion handler to receive the data and the error objects
     */
    public class func verifyEmailChangeToken(request request: VerifyEmailChangeTokenRequest, completion: ((error: ErrorType?) -> Void)) {
        verifyEmailChangeTokenWithRequestBuilder(request: request).execute { (response, error) -> Void in
            completion(error: error);
        }
    }


    /**
     
     Verify Email Change Token.
     
     - POST /operators/email_change_token/verify
     - Verifies the token for the e-mail address change, and then changes the e-mail address.
     - API Key:
       - type: apiKey X-Soracom-API-Key 
       - name: api_key
     - API Key:
       - type: apiKey X-Soracom-Token 
       - name: api_token
     
     - parameter request: (body) request 

     - returns: RequestBuilder<Void> 
     */
    public class func verifyEmailChangeTokenWithRequestBuilder(request request: VerifyEmailChangeTokenRequest) -> RequestBuilder<Void> {
        let path = "/operators/email_change_token/verify"
        let URLString = SwaggerClientAPI.basePath + path
        
        let parameters = request.encodeToJSON() as? [String:AnyObject]
 
        let convertedParameters = APIHelper.convertBoolToString(parameters)
 
        let requestBuilder: RequestBuilder<Void>.Type = SwaggerClientAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "POST", URLString: URLString, parameters: convertedParameters, isBody: true)
    }

    
    
    
    /**
     
     Verify Operator.
     
     - parameter token: (body) token 
     - parameter completion: completion handler to receive the data and the error objects
     */
    public class func verifyOperator(token token: VerifyOperatorsRequest, completion: ((error: ErrorType?) -> Void)) {
        verifyOperatorWithRequestBuilder(token: token).execute { (response, error) -> Void in
            completion(error: error);
        }
    }


    /**
     
     Verify Operator.
     
     - POST /operators/verify
     - Verifies the operator's registration. Called by setting as parameter the one-time verification token received via e-mail.
     
     - parameter token: (body) token 

     - returns: RequestBuilder<Void> 
     */
    public class func verifyOperatorWithRequestBuilder(token token: VerifyOperatorsRequest) -> RequestBuilder<Void> {
        let path = "/operators/verify"
        let URLString = SwaggerClientAPI.basePath + path
        
        let parameters = token.encodeToJSON() as? [String:AnyObject]
 
        let convertedParameters = APIHelper.convertBoolToString(parameters)
 
        let requestBuilder: RequestBuilder<Void>.Type = SwaggerClientAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "POST", URLString: URLString, parameters: convertedParameters, isBody: true)
    }

}
