//
// PaymentAPI.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Alamofire



public class PaymentAPI: APIBase {
    
    /**
     
     Activate payment method.
     
     - parameter completion: completion handler to receive the data and the error objects
     */
    public class func activatePaymentMethod(completion: ((data: AnyObject?, error: ErrorType?) -> Void)) {
        activatePaymentMethodWithRequestBuilder().execute { (response, error) -> Void in
            completion(data: response?.body, error: error);
        }
    }


    /**
     
     Activate payment method.
     
     - POST /payment_methods/current/activate
     - Activates a current payment method that has an error.
     - API Key:
       - type: apiKey X-Soracom-API-Key 
       - name: api_key
     - API Key:
       - type: apiKey X-Soracom-Token 
       - name: api_token
     - examples: [{contentType=application/json;charset=UTF-8, example="{}"}]

     - returns: RequestBuilder<AnyObject> 
     */
    public class func activatePaymentMethodWithRequestBuilder() -> RequestBuilder<AnyObject> {
        let path = "/payment_methods/current/activate"
        let URLString = SwaggerClientAPI.basePath + path
        
        let nillableParameters: [String:AnyObject?] = [:]
 
        let parameters = APIHelper.rejectNil(nillableParameters)
 
        let convertedParameters = APIHelper.convertBoolToString(parameters)
 
        let requestBuilder: RequestBuilder<AnyObject>.Type = SwaggerClientAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "POST", URLString: URLString, parameters: convertedParameters, isBody: true)
    }

    
    /**
     
     Get payment method information
     
     - parameter completion: completion handler to receive the data and the error objects
     */
    public class func getPaymentMethod(completion: ((data: GetPaymentMethodResult?, error: ErrorType?) -> Void)) {
        getPaymentMethodWithRequestBuilder().execute { (response, error) -> Void in
            completion(data: response?.body, error: error);
        }
    }


    /**
     
     Get payment method information
     
     - GET /payment_methods/current
     - Returns current payment methods. Detailed information is included in the properties.
     - API Key:
       - type: apiKey X-Soracom-API-Key 
       - name: api_key
     - API Key:
       - type: apiKey X-Soracom-Token 
       - name: api_token
     - examples: [{contentType=application/json;charset=UTF-8, example={
  "updateDate" : "yyyyMMddHHmmss",
  "errorMessage" : "aeiou",
  "errorCode" : "aeiou",
  "properties" : "aeiou",
  "providerType" : "aeiou"
}}]

     - returns: RequestBuilder<GetPaymentMethodResult> 
     */
    public class func getPaymentMethodWithRequestBuilder() -> RequestBuilder<GetPaymentMethodResult> {
        let path = "/payment_methods/current"
        let URLString = SwaggerClientAPI.basePath + path
        
        let nillableParameters: [String:AnyObject?] = [:]
 
        let parameters = APIHelper.rejectNil(nillableParameters)
 
        let convertedParameters = APIHelper.convertBoolToString(parameters)
 
        let requestBuilder: RequestBuilder<GetPaymentMethodResult>.Type = SwaggerClientAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "GET", URLString: URLString, parameters: convertedParameters, isBody: true)
    }

    
    
    
    /**
     
     Get payment transaction result.
     
     - parameter paymentTransactionId: (path) payment_transaction_id 
     - parameter completion: completion handler to receive the data and the error objects
     */
    public class func getPaymentTransaction(paymentTransactionId paymentTransactionId: String, completion: ((data: GetPaymentTransactionResult?, error: ErrorType?) -> Void)) {
        getPaymentTransactionWithRequestBuilder(paymentTransactionId: paymentTransactionId).execute { (response, error) -> Void in
            completion(data: response?.body, error: error);
        }
    }


    /**
     
     Get payment transaction result.
     
     - GET /payment_history/transactions/{paymentTransactionId}
     - Returns result of a payment transaction.
     - API Key:
       - type: apiKey X-Soracom-API-Key 
       - name: api_key
     - API Key:
       - type: apiKey X-Soracom-Token 
       - name: api_token
     - examples: [{contentType=application/json;charset=UTF-8, example={
  "amount" : {
    "totalAmount" : 1.3579000000000001069366817318950779736042022705078125,
    "taxAmount" : 1.3579000000000001069366817318950779736042022705078125
  },
  "description" : {
    "description" : "aeiou",
    "itemList" : [ "aeiou" ]
  },
  "messageCode" : "aeiou",
  "message" : "aeiou",
  "status" : "aeiou"
}}]
     
     - parameter paymentTransactionId: (path) payment_transaction_id 

     - returns: RequestBuilder<GetPaymentTransactionResult> 
     */
    public class func getPaymentTransactionWithRequestBuilder(paymentTransactionId paymentTransactionId: String) -> RequestBuilder<GetPaymentTransactionResult> {
        var path = "/payment_history/transactions/{paymentTransactionId}"
        path = path.stringByReplacingOccurrencesOfString("{paymentTransactionId}", withString: "\(paymentTransactionId)", options: .LiteralSearch, range: nil)
        let URLString = SwaggerClientAPI.basePath + path
        
        let nillableParameters: [String:AnyObject?] = [:]
 
        let parameters = APIHelper.rejectNil(nillableParameters)
 
        let convertedParameters = APIHelper.convertBoolToString(parameters)
 
        let requestBuilder: RequestBuilder<GetPaymentTransactionResult>.Type = SwaggerClientAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "GET", URLString: URLString, parameters: convertedParameters, isBody: true)
    }

    
    /**
     
     List coupons.
     
     - parameter completion: completion handler to receive the data and the error objects
     */
    public class func listCoupons(completion: ((data: ListCouponResponse?, error: ErrorType?) -> Void)) {
        listCouponsWithRequestBuilder().execute { (response, error) -> Void in
            completion(data: response?.body, error: error);
        }
    }


    /**
     
     List coupons.
     
     - GET /coupons
     - Returns a list of currently registered coupons.
     - API Key:
       - type: apiKey X-Soracom-API-Key 
       - name: api_key
     - API Key:
       - type: apiKey X-Soracom-Token 
       - name: api_token
     - examples: [{contentType=application/json;charset=UTF-8, example={
  "couponList" : [ {
    "amount" : 1.3579000000000001069366817318950779736042022705078125,
    "balance" : 1.3579000000000001069366817318950779736042022705078125,
    "billItemName" : "aeiou",
    "expiryYearMonth" : "yyyyMM",
    "couponCode" : "aeiou"
  } ]
}}]

     - returns: RequestBuilder<ListCouponResponse> 
     */
    public class func listCouponsWithRequestBuilder() -> RequestBuilder<ListCouponResponse> {
        let path = "/coupons"
        let URLString = SwaggerClientAPI.basePath + path
        
        let nillableParameters: [String:AnyObject?] = [:]
 
        let parameters = APIHelper.rejectNil(nillableParameters)
 
        let convertedParameters = APIHelper.convertBoolToString(parameters)
 
        let requestBuilder: RequestBuilder<ListCouponResponse>.Type = SwaggerClientAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "GET", URLString: URLString, parameters: convertedParameters, isBody: true)
    }

    
    
    
    /**
     
     Register Coupon.
     
     - parameter couponCode: (path) coupon_code 
     - parameter completion: completion handler to receive the data and the error objects
     */
    public class func registerCoupon(couponCode couponCode: String, completion: ((data: CouponResponse?, error: ErrorType?) -> Void)) {
        registerCouponWithRequestBuilder(couponCode: couponCode).execute { (response, error) -> Void in
            completion(data: response?.body, error: error);
        }
    }


    /**
     
     Register Coupon.
     
     - POST /coupons/{couponCode}/register
     - Registers a coupon.
     - API Key:
       - type: apiKey X-Soracom-API-Key 
       - name: api_key
     - API Key:
       - type: apiKey X-Soracom-Token 
       - name: api_token
     - examples: [{contentType=application/json;charset=UTF-8, example={
  "amount" : 1.3579000000000001069366817318950779736042022705078125,
  "balance" : 1.3579000000000001069366817318950779736042022705078125,
  "billItemName" : "aeiou",
  "expiryYearMonth" : "yyyyMM",
  "couponCode" : "aeiou"
}}]
     
     - parameter couponCode: (path) coupon_code 

     - returns: RequestBuilder<CouponResponse> 
     */
    public class func registerCouponWithRequestBuilder(couponCode couponCode: String) -> RequestBuilder<CouponResponse> {
        var path = "/coupons/{couponCode}/register"
        path = path.stringByReplacingOccurrencesOfString("{couponCode}", withString: "\(couponCode)", options: .LiteralSearch, range: nil)
        let URLString = SwaggerClientAPI.basePath + path
        
        let nillableParameters: [String:AnyObject?] = [:]
 
        let parameters = APIHelper.rejectNil(nillableParameters)
 
        let convertedParameters = APIHelper.convertBoolToString(parameters)
 
        let requestBuilder: RequestBuilder<CouponResponse>.Type = SwaggerClientAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "POST", URLString: URLString, parameters: convertedParameters, isBody: true)
    }

    
    
    
    /**
     
     Register credit card information for WebPay.
     
     - parameter creditCard: (body) creditCard 
     - parameter completion: completion handler to receive the data and the error objects
     */
    public class func registerWebPayPaymentMethod(creditCard creditCard: CreditCard, completion: ((data: AnyObject?, error: ErrorType?) -> Void)) {
        registerWebPayPaymentMethodWithRequestBuilder(creditCard: creditCard).execute { (response, error) -> Void in
            completion(data: response?.body, error: error);
        }
    }


    /**
     
     Register credit card information for WebPay.
     
     - POST /payment_methods/webpay
     - Registers credit card information for WebPay payments.
     - API Key:
       - type: apiKey X-Soracom-API-Key 
       - name: api_key
     - API Key:
       - type: apiKey X-Soracom-Token 
       - name: api_token
     - examples: [{contentType=application/json, example="{}"}]
     
     - parameter creditCard: (body) creditCard 

     - returns: RequestBuilder<AnyObject> 
     */
    public class func registerWebPayPaymentMethodWithRequestBuilder(creditCard creditCard: CreditCard) -> RequestBuilder<AnyObject> {
        let path = "/payment_methods/webpay"
        let URLString = SwaggerClientAPI.basePath + path
        
        let parameters = creditCard.encodeToJSON() as? [String:AnyObject]
 
        let convertedParameters = APIHelper.convertBoolToString(parameters)
 
        let requestBuilder: RequestBuilder<AnyObject>.Type = SwaggerClientAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "POST", URLString: URLString, parameters: convertedParameters, isBody: true)
    }

}
