//
// Generated by SwagGen
// https://github.com/yonaskolb/SwagGen
//

import Foundation

extension Request where T == [AuthKeyResponse] {

    /**
        List User AuthKeys.

        Returns the SAM user's AuthKey list.

        [API Documentation](https://dev.soracom.io/en/docs/api/#!/User/listUserAuthKeys)
    */
    public class func listUserAuthKeys(
        
        operatorId: String,
        userName: String,
        responseHandler: ResponseHandler<[AuthKeyResponse]>? = nil
    ) ->   Request<[AuthKeyResponse]> {

        let path  = "/operators/\(operatorId)/users/\(userName)/auth_keys"

        let requestObject = Request<[AuthKeyResponse]>.init(path, responseHandler: responseHandler)

        
        requestObject.expectedHTTPStatus = 200
        requestObject.method = .get


        return requestObject
    }

}
