//
// Generated by SwagGen
// https://github.com/yonaskolb/SwagGen
//

import Foundation

public final class SetNetworkSetRequest: Codable, Equatable {

    public var networkSetId: String?

    public init(networkSetId: String? = nil) {
        self.networkSetId = networkSetId
    }

    private enum CodingKeys: String, CodingKey {
        case networkSetId
    }

    public required init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: CodingKeys.self)

        networkSetId = try container.decodeIfPresent(.networkSetId)
    }

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)

        try container.encodeIfPresent(networkSetId, forKey: .networkSetId)
    }

    public func isEqual(to object: Any?) -> Bool {
      guard let object = object as? SetNetworkSetRequest else { return false }
      guard self.networkSetId == object.networkSetId else { return false }
      return true
    }

    public static func == (lhs: SetNetworkSetRequest, rhs: SetNetworkSetRequest) -> Bool {
        return lhs.isEqual(to: rhs)
    }
}
