//
// Generated by SwagGen
// https://github.com/yonaskolb/SwagGen
//

import Foundation

public final class VerifyEmailChangeTokenRequest: Codable, Equatable {

    public var token: String

    public init(token: String) {
        self.token = token
    }

    private enum CodingKeys: String, CodingKey {
        case token
    }

    public required init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: CodingKeys.self)

        token = try container.decode(.token)
    }

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)

        try container.encode(token, forKey: .token)
    }

    public func isEqual(to object: Any?) -> Bool {
      guard let object = object as? VerifyEmailChangeTokenRequest else { return false }
      guard self.token == object.token else { return false }
      return true
    }

    public static func == (lhs: VerifyEmailChangeTokenRequest, rhs: VerifyEmailChangeTokenRequest) -> Bool {
        return lhs.isEqual(to: rhs)
    }
}
