//
// Generated by SwagGen
// https://github.com/yonaskolb/SwagGen
//

import Foundation

extension Request {

    /**
        Delete User AuthKey.

        Deletes an AuthKey from the SAM user.

        Docs: https://dev.soracom.io/en/docs/api/#!/User/deleteUserAuthKey
    */
    public class func _deleteUserAuthKey(
        
        operatorId: String,
        userName: String,
        authKeyId: String,
        responseHandler: ResponseHandler<NoResponseBody>? = nil
    ) ->   Request<NoResponseBody> {

        let path  = "/operators/\(operatorId)/users/\(userName)/auth_keys/\(authKeyId)"

        let requestObject = Request<NoResponseBody>.init(path, responseHandler: responseHandler)

        
        requestObject.expectedHTTPStatus = 200
        requestObject.method = .delete


        return requestObject
    }

}
