//
// Generated by SwagGen
// https://github.com/yonaskolb/SwagGen
//

import Foundation

extension Request {

    public class func _getUserAuthKey(
        
        operatorId: String,
        userName: String,
        authKeyId: String,
        responseHandler: ResponseHandler<AuthKeyResponse>? = nil
    ) ->   Request<AuthKeyResponse> {

        let path = "/operators/{operator_id}/users/{user_name}/auth_keys/{auth_key_id}".replacingOccurrences(of: "{" + "operatorId" + "}", with: "\(operatorId)").replacingOccurrences(of: "{" + "userName" + "}", with: "\(userName)").replacingOccurrences(of: "{" + "authKeyId" + "}", with: "\(authKeyId)") // This nonsense should be fixed in the code generator, we might do a PR for at some point...

        let requestObject = Request<AuthKeyResponse>.init(path, responseHandler: responseHandler)

        
        requestObject.expectedHTTPStatus = 200
        requestObject.method = .get


        return requestObject
    }

}
