//
// Generated by SwagGen
// https://github.com/yonaskolb/SwagGen
//

import Foundation

extension Request {

    public class func _getUserPermission(
        
        operatorId: String,
        userName: String,
        responseHandler: ResponseHandler<GetUserPermissionResponse>? = nil
    ) ->   Request<GetUserPermissionResponse> {

    let path = "/operators/{operator_id}/users/{user_name}/permission".replacingOccurrences(of: "{" + "operator_id" + "}", with: "\(operatorId)").replacingOccurrences(of: "{" + "user_name" + "}", with: "\(userName)")
      // FIXME: This path-expansion nonsense should be done in the code generation step (custom Stencil filter maybe?), and not done at all to paths that don't need it...

        let requestObject = Request<GetUserPermissionResponse>.init(path, responseHandler: responseHandler)

        
        requestObject.expectedHTTPStatus = 200
        requestObject.method = .get


        return requestObject
    }

}
