//
// Generated by SwagGen
// https://github.com/yonaskolb/SwagGen
//

import Foundation

extension Request {

    public class func _getUserAuthKey(
        
        operatorId: String,
        userName: String,
        authKeyId: String,
        responseHandler: ResponseHandler<AuthKeyResponse>? = nil
    ) ->   Request<AuthKeyResponse> {

    let path = "/operators/{operator_id}/users/{user_name}/auth_keys/{auth_key_id}".replacingOccurrences(of: "{" + "operator_id" + "}", with: "\(operatorId)").replacingOccurrences(of: "{" + "user_name" + "}", with: "\(userName)").replacingOccurrences(of: "{" + "auth_key_id" + "}", with: "\(authKeyId)")
      // FIXME: This path-expansion nonsense should be done in the code generation step (custom Stencil filter maybe?), and not done at all to paths that don't need it...

        let requestObject = Request<AuthKeyResponse>.init(path, responseHandler: responseHandler)

        
        requestObject.expectedHTTPStatus = 200
        requestObject.method = .get


        return requestObject
    }

}
