//
// Generated by SwagGen
// https://github.com/yonaskolb/SwagGen
//

import Foundation

extension Request {

    public class func _listUsers(
        
        operatorId: String,
        responseHandler: ResponseHandler<[UserDetailResponse]>? = nil
    ) ->   Request<[UserDetailResponse]> {

        let path  = "/operators/\(operatorId)/users"

        let requestObject = Request<[UserDetailResponse]>.init(path, responseHandler: responseHandler)

        
        requestObject.expectedHTTPStatus = 200
        requestObject.method = .get


        return requestObject
    }

}
