//
// Generated by SwagGen
// https://github.com/yonaskolb/SwagGen
//

import Foundation

extension Request {

    public class func _getPaymentMethod(
        
        responseHandler: ResponseHandler<GetPaymentMethodResult>? = nil
    ) ->   Request<GetPaymentMethodResult> {

        let path = "/payment_methods/current" // This nonsense should be fixed in the code generator, we might do a PR for at some point...

        let requestObject = Request<GetPaymentMethodResult>.init(path, responseHandler: responseHandler)

        
        requestObject.expectedHTTPStatus = 200
        requestObject.method = .get


        return requestObject
    }

}
