//
// Generated by SwagGen
// https://github.com/yonaskolb/SwagGen
//

import Foundation

extension Request {

    public class func _registerCoupon(
        
        couponCode: String,
        responseHandler: ResponseHandler<CouponResponse>? = nil
    ) ->   Request<CouponResponse> {

    let path = "/coupons/{coupon_code}/register".replacingOccurrences(of: "{" + "coupon_code" + "}", with: "\(couponCode)")
      // FIXME: This path-expansion nonsense should be done in the code generation step (custom Stencil filter maybe?), and not done at all to paths that don't need it...

        let requestObject = Request<CouponResponse>.init(path, responseHandler: responseHandler)

        
        requestObject.expectedHTTPStatus = 200
        requestObject.method = .post


        return requestObject
    }

}
