//
// Generated by SwagGen
// https://github.com/yonaskolb/SwagGen
//

import Foundation

extension Request {

    public class func _searchSubscribers(
        
        name: [String]? = nil,
        group: [String]? = nil,
        imsi: [String]? = nil,
        msisdn: [String]? = nil,
        iccid: [String]? = nil,
        serialNumber: [String]? = nil,
        tag: [String]? = nil,
        limit: Int? = nil,
        lastEvaluatedKey: String? = nil,
        searchType: SearchType? = nil,
        responseHandler: ResponseHandler<[Subscriber]>? = nil
    ) ->   Request<[Subscriber]> {

        let path = "/query/subscribers" // This nonsense should be fixed in the code generator, we might do a PR for at some point...

        let requestObject = Request<[Subscriber]>.init(path, responseHandler: responseHandler)

        
        requestObject.expectedHTTPStatus = 200
        requestObject.method = .get

        requestObject.query = makeQueryDictionary([
            "name": name as Any,
            "group": group as Any,
            "imsi": imsi as Any,
            "msisdn": msisdn as Any,
            "iccid": iccid as Any,
            "serialNumber": serialNumber as Any,
            "tag": tag as Any,
            "limit": limit as Any,
            "lastEvaluatedKey": lastEvaluatedKey as Any,
            "searchType": searchType as Any
        ])

        return requestObject
    }

}
