//
// Generated by SwagGen
// https://github.com/yonaskolb/SwagGen
//

import Foundation

extension Request {

    public class func _listDevices(
        
        tagName: String? = nil,
        tagValue: String? = nil,
        tagValueMatchMode: String? = nil,
        lastEvaluatedKey: String? = nil,
        limit: Int? = nil,
        responseHandler: ResponseHandler<[Device]>? = nil
    ) ->   Request<[Device]> {

        let path = "/devices" // This nonsense should be fixed in the code generator, we might do a PR for at some point...

        let requestObject = Request<[Device]>.init(path, responseHandler: responseHandler)

        
        requestObject.expectedHTTPStatus = 200
        requestObject.method = .get

        requestObject.query = makeQueryDictionary([
            "tagName": tagName,
            "tagValue": tagValue,
            "tagValueMatchMode": tagValueMatchMode,
            "lastEvaluatedKey": lastEvaluatedKey,
            "limit": limit
        ])

        return requestObject
    }

}
