//
// Generated by SwagGen
// https://github.com/yonaskolb/SwagGen
//

import Foundation

extension Request {

    public class func _listDevices(
        
        tagName: String? = nil,
        tagValue: String? = nil,
        tagValueMatchMode: String? = nil,
        lastEvaluatedKey: String? = nil,
        limit: Int? = nil,
        responseHandler: ResponseHandler<[Device]>? = nil
    ) ->   Request<[Device]> {

    let path = "/devices"
      // FIXME: This path-expansion nonsense should be done in the code generation step (custom Stencil filter maybe?), and not done at all to paths that don't need it...

        let requestObject = Request<[Device]>.init(path, responseHandler: responseHandler)

        
        requestObject.expectedHTTPStatus = 200
        requestObject.method = .get

        requestObject.query = makeQueryDictionary([
            "tagName": tagName,
            "tagValue": tagValue,
            "tagValueMatchMode": tagValueMatchMode,
            "lastEvaluatedKey": lastEvaluatedKey,
            "limit": limit
        ])

        return requestObject
    }

}
