//
// Generated by SwagGen
// https://github.com/yonaskolb/SwagGen
//

import Foundation

extension Request {

    public class func _unobserveDeviceResources(
        
        deviceId: String,
        object: String,
        instance: String,
        responseHandler: ResponseHandler<NoResponseBody>? = nil
    ) ->   Request<NoResponseBody> {

        let path = "/devices/{device_id}/{object}/{instance}/unobserve".replacingOccurrences(of: "{" + "deviceId" + "}", with: "\(deviceId)").replacingOccurrences(of: "{" + "object" + "}", with: "\(object)").replacingOccurrences(of: "{" + "instance" + "}", with: "\(instance)") // This nonsense should be fixed in the code generator, we might do a PR for at some point...

        let requestObject = Request<NoResponseBody>.init(path, responseHandler: responseHandler)

        
        requestObject.expectedHTTPStatus = 204
        requestObject.method = .post


        return requestObject
    }

}
