//
// Generated by SwagGen
// https://github.com/yonaskolb/SwagGen
//

import Foundation

extension Request {

    public class func _auth(
        auth: AuthRequest, 
        responseHandler: ResponseHandler<AuthResponse>? = nil
    ) ->   Request<AuthResponse> {

        let path  = "/auth"

        let requestObject = Request<AuthResponse>.init(path, responseHandler: responseHandler)

        requestObject.messageBody = auth.toData()
        requestObject.expectedHTTPStatus = 200
        requestObject.method = .post


        return requestObject
    }

}
