//
// Generated by SwagGen
// https://github.com/yonaskolb/SwagGen
//

import Foundation

extension Request {

    /**
        Delete Operator

        To remove the Operator.

        Docs: https://dev.soracom.io/en/docs/api/#!/Operator/deleteSandboxOperator
    */
    public class func _deleteSandboxOperator(
        
        operatorId: String,
        responseHandler: ResponseHandler<NoResponseBody>? = nil
    ) ->   Request<NoResponseBody> {

        let path  = "/sandbox/operators/\(operatorId)"

        let requestObject = Request<NoResponseBody>.init(path, responseHandler: responseHandler)

        
        requestObject.expectedHTTPStatus = 200
        requestObject.method = .delete


        return requestObject
    }

}
