//
// Generated by SwagGen
// https://github.com/yonaskolb/SwagGen
//

import Foundation

extension Request {

    public class func _generateAuthToken(
        request: GenerateTokenRequest, 
        operatorId: String,
        responseHandler: ResponseHandler<GenerateTokenResponse>? = nil
    ) ->   Request<GenerateTokenResponse> {

        let path  = "/operators/\(operatorId)/token"

        let requestObject = Request<GenerateTokenResponse>.init(path, responseHandler: responseHandler)

        requestObject.messageBody = request.toData()
        requestObject.expectedHTTPStatus = 200
        requestObject.method = .post


        return requestObject
    }

}
