//
// Generated by SwagGen
// https://github.com/yonaskolb/SwagGen
//

import Foundation

extension Request {

    public class func _initializeOperator(
        request: InitRequest, 
        responseHandler: ResponseHandler<AuthResponse>? = nil
    ) ->   Request<AuthResponse> {

        let path  = "/sandbox/init"

        let requestObject = Request<AuthResponse>.init(path, responseHandler: responseHandler)

        requestObject.messageBody = request.toData()
        requestObject.expectedHTTPStatus = 201
        requestObject.method = .post


        return requestObject
    }

}
