//
// Generated by SwagGen
// https://github.com/yonaskolb/SwagGen
//

import Foundation

extension Request {

    public class func _createCredential(
        credentials: CreateAndUpdateCredentialsModel, 
        credentialsId: String,
        responseHandler: ResponseHandler<CredentialsModel>? = nil
    ) ->   Request<CredentialsModel> {

        let path  = "/credentials/\(credentialsId)"

        let requestObject = Request<CredentialsModel>.init(path, responseHandler: responseHandler)

        requestObject.messageBody = credentials.toData()
        requestObject.expectedHTTPStatus = 201
        requestObject.method = .post


        return requestObject
    }

}
