//
// Generated by SwagGen
// https://github.com/yonaskolb/SwagGen
//

import Foundation

extension Request {

    public class func _putConfigurationParameters(
        parameters: [GroupConfigurationUpdateRequest], 
        groupId: String,
        namespace: Namespace,
        responseHandler: ResponseHandler<Group>? = nil
    ) ->   Request<Group> {

        let path = "/groups/{group_id}/configuration/{namespace}".replacingOccurrences(of: "{" + "groupId" + "}", with: "\(groupId)").replacingOccurrences(of: "{" + "namespace" + "}", with: "\(namespace.encode())") // This nonsense should be fixed in the code generator, we might do a PR for at some point...

        let requestObject = Request<Group>.init(path, responseHandler: responseHandler)

        requestObject.messageBody = parameters.toData()
        requestObject.expectedHTTPStatus = 200
        requestObject.method = .put


        return requestObject
    }

}
