//
// Generated by SwagGen
// https://github.com/yonaskolb/SwagGen
//

import Foundation

open class _AirStatsResponse: Codable, Equatable {

    open var dataTrafficStatsMap: [String: DataTrafficStats]?

    open var date: String?

    open var unixtime: Int?

    public init(dataTrafficStatsMap: [String: DataTrafficStats]? = nil, date: String? = nil, unixtime: Int? = nil) {
        self.dataTrafficStatsMap = dataTrafficStatsMap
        self.date = date
        self.unixtime = unixtime
    }

    private enum CodingKeys: String, CodingKey {
        case dataTrafficStatsMap
        case date
        case unixtime
    }

    public required init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: CodingKeys.self)

        dataTrafficStatsMap = try container.decodeIfPresent(.dataTrafficStatsMap)
        date = try container.decodeIfPresent(.date)
        unixtime = try container.decodeIfPresent(.unixtime)
    }

    open func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)

        try container.encodeIfPresent(dataTrafficStatsMap, forKey: .dataTrafficStatsMap)
        try container.encodeIfPresent(date, forKey: .date)
        try container.encodeIfPresent(unixtime, forKey: .unixtime)
    }

    public func isEqual(to object: Any?) -> Bool {
      guard let object = object as? _AirStatsResponse else { return false }
      guard self.dataTrafficStatsMap == object.dataTrafficStatsMap else { return false }
      guard self.date == object.date else { return false }
      guard self.unixtime == object.unixtime else { return false }
      return true
    }

    public static func == (lhs: _AirStatsResponse, rhs: _AirStatsResponse) -> Bool {
        return lhs.isEqual(to: rhs)
    }
}
