//
// Generated by SwagGen
// https://github.com/yonaskolb/SwagGen
//

import Foundation

open class _LoraData: Codable, Equatable {

    open var data: String?

    open var fPort: Int?

    public init(data: String? = nil, fPort: Int? = nil) {
        self.data = data
        self.fPort = fPort
    }

    private enum CodingKeys: String, CodingKey {
        case data
        case fPort
    }

    public required init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: CodingKeys.self)

        data = try container.decodeIfPresent(.data)
        fPort = try container.decodeIfPresent(.fPort)
    }

    open func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)

        try container.encodeIfPresent(data, forKey: .data)
        try container.encodeIfPresent(fPort, forKey: .fPort)
    }

    public func isEqual(to object: Any?) -> Bool {
      guard let object = object as? _LoraData else { return false }
      guard self.data == object.data else { return false }
      guard self.fPort == object.fPort else { return false }
      return true
    }

    public static func == (lhs: _LoraData, rhs: _LoraData) -> Bool {
        return lhs.isEqual(to: rhs)
    }
}
