//
// Generated by SwagGen
// https://github.com/yonaskolb/SwagGen
//

import Foundation

extension Request where T == Group {

    /**
        Get Group.

        Returns the group specified by the group ID.

        Docs: https://dev.soracom.io/en/docs/api/#!/Group/getGroup
    */
    public class func getGroup(
        
        groupId: String,
        responseHandler: ResponseHandler<Group>? = nil
    ) ->   Request<Group> {

        let path  = "/groups/\(groupId)"

        let requestObject = Request<Group>.init(path, responseHandler: responseHandler)

        
        requestObject.expectedHTTPStatus = 200
        requestObject.method = .get


        return requestObject
    }

}
