//
// Generated by SwagGen
// https://github.com/yonaskolb/SwagGen
//

import Foundation

extension Request {

    public class func _listSubscribers(
        
        tagName: String? = nil,
        tagValue: String? = nil,
        tagValueMatchMode: FUNKMASTER? = nil,
        statusFilter: String? = nil,
        speedClassFilter: String? = nil,
        serialNumberFilter: String? = nil,
        limit: Int? = nil,
        lastEvaluatedKey: String? = nil,
        responseHandler: ResponseHandler<[Subscriber]>? = nil
    ) ->   Request<[Subscriber]> {

    let path = "/subscribers"
      // FIXME: This path-expansion nonsense should be done in the code generation step (custom Stencil filter maybe?), and not done at all to paths that don't need it...

        let requestObject = Request<[Subscriber]>.init(path, responseHandler: responseHandler)

        
        requestObject.expectedHTTPStatus = 200
        requestObject.method = .get

        requestObject.query = makeQueryDictionary([
            "tagName": tagName,
            "tagValue": tagValue,
            "tagValueMatchMode": tagValueMatchMode,
            "statusFilter": statusFilter,
            "speedClassFilter": speedClassFilter,
            "serialNumberFilter": serialNumberFilter,
            "limit": limit,
            "lastEvaluatedKey": lastEvaluatedKey
        ])

        return requestObject
    }

}
