//
// Generated by SwagGen
// https://github.com/yonaskolb/SwagGen
//

import Foundation

extension Request {

    public class func _sendSms(
        smsForwardingRequest: SmsForwardingRequest, 
        imsi: String,
        responseHandler: ResponseHandler<SmsForwardingReport>? = nil
    ) ->   Request<SmsForwardingReport> {

        let path  = "/subscribers/\(imsi)/send_sms"

        let requestObject = Request<SmsForwardingReport>.init(path, responseHandler: responseHandler)

        requestObject.messageBody = smsForwardingRequest.toData()
        requestObject.expectedHTTPStatus = 202
        requestObject.method = .post


        return requestObject
    }

}
