//
// Generated by SwagGen
// https://github.com/yonaskolb/SwagGen
//

import Foundation

extension Request {

    public class func _verifySubscriberTransferToken(
        token: VerifySubscriberTransferTokenRequest, 
        responseHandler: ResponseHandler<VerifySubscriberTransferTokenResponse>? = nil
    ) ->   Request<VerifySubscriberTransferTokenResponse> {

        let path  = "/subscribers/transfer_token/verify"

        let requestObject = Request<VerifySubscriberTransferTokenResponse>.init(path, responseHandler: responseHandler)

        requestObject.messageBody = token.toData()
        requestObject.expectedHTTPStatus = 200
        requestObject.method = .post


        return requestObject
    }

}
