//
// Generated by SwagGen
// https://github.com/yonaskolb/SwagGen
//

import Foundation

extension Request where T == NoResponseBody {

    /**
        Unregister VPG gate peer

        Unregister a gate peer from the Virtual Private Gateway

        Docs: https://dev.soracom.io/en/docs/api/#!/VirtualPrivateGateway/unregisterGatePeer
    */
    public class func unregisterGatePeer(
        
        vpgId: String,
        outerIpAddress: String,
        responseHandler: ResponseHandler<NoResponseBody>? = nil
    ) ->   Request<NoResponseBody> {

        let path  = "/virtual_private_gateways/\(vpgId)/gate/peers/\(outerIpAddress)"

        let requestObject = Request<NoResponseBody>.init(path, responseHandler: responseHandler)

        
        requestObject.expectedHTTPStatus = 204
        requestObject.method = .delete


        return requestObject
    }

}
