//
// Generated by SwagGen
// https://github.com/yonaskolb/SwagGen
//

import Foundation

extension Request {

    public class func _sendDataToLoraDevice(
        data: LoraData, 
        deviceId: String,
        responseHandler: ResponseHandler<NoResponseBody>? = nil
    ) ->   Request<NoResponseBody> {

        let path  = "/lora_devices/\(deviceId)/data"

        let requestObject = Request<NoResponseBody>.init(path, responseHandler: responseHandler)

        requestObject.messageBody = data.toData()
        requestObject.expectedHTTPStatus = 204
        requestObject.method = .post


        return requestObject
    }

}
