//
// Generated by SwagGen
// https://github.com/yonaskolb/SwagGen
//

import Foundation

extension Request {

    public class func _createShippingAddress(
        model: ShippingAddressModel, 
        operatorId: String,
        responseHandler: ResponseHandler<String>? = nil
    ) ->   Request<String> {

    let path = "/operators/{operator_id}/shipping_addresses".replacingOccurrences(of: "{" + "operator_id" + "}", with: "\(operatorId)")
      // FIXME: This path-expansion nonsense should be done in the code generation step (custom Stencil filter maybe?), and not done at all to paths that don't need it...

        let requestObject = Request<String>.init(path, responseHandler: responseHandler)

        requestObject.messageBody = model.toData()
        requestObject.expectedHTTPStatus = 200
        requestObject.method = .post


        return requestObject
    }

}
