//
// Generated by SwagGen
// https://github.com/yonaskolb/SwagGen
//

import Foundation

extension Request {

    /**
        Delete shipping address.

        Deletes a shipping address.

        Docs: https://dev.soracom.io/en/docs/api/#!/ShippingAddress/deleteShippingAddress
    */
    public class func _deleteShippingAddress(
        
        operatorId: String,
        shippingAddressId: String,
        responseHandler: ResponseHandler<NoResponseBody>? = nil
    ) ->   Request<NoResponseBody> {

        let path  = "/operators/\(operatorId)/shipping_addresses/\(shippingAddressId)"

        let requestObject = Request<NoResponseBody>.init(path, responseHandler: responseHandler)

        
        requestObject.expectedHTTPStatus = 200
        requestObject.method = .delete


        return requestObject
    }

}
