//
// Generated by SwagGen
// https://github.com/yonaskolb/SwagGen
//

import Foundation

extension Request {

    public class func _getShippingAddress(
        
        operatorId: String,
        shippingAddressId: String,
        responseHandler: ResponseHandler<GetShippingAddressResponse>? = nil
    ) ->   Request<GetShippingAddressResponse> {

        let path = "/operators/{operator_id}/shipping_addresses/{shipping_address_id}".replacingOccurrences(of: "{" + "operatorId" + "}", with: "\(operatorId)").replacingOccurrences(of: "{" + "shippingAddressId" + "}", with: "\(shippingAddressId)") // This nonsense should be fixed in the code generator, we might do a PR for at some point...

        let requestObject = Request<GetShippingAddressResponse>.init(path, responseHandler: responseHandler)

        
        requestObject.expectedHTTPStatus = 200
        requestObject.method = .get


        return requestObject
    }

}
