//
// Generated by SwagGen
// https://github.com/yonaskolb/SwagGen
//

import Foundation

extension Request {

    public class func _listShippingAddresses(
        
        operatorId: String,
        responseHandler: ResponseHandler<ListShippingAddressResponse>? = nil
    ) ->   Request<ListShippingAddressResponse> {

        let path  = "/operators/\(operatorId)/shipping_addresses"

        let requestObject = Request<ListShippingAddressResponse>.init(path, responseHandler: responseHandler)

        
        requestObject.expectedHTTPStatus = 200
        requestObject.method = .get


        return requestObject
    }

}
