//
// Generated by SwagGen
// https://github.com/yonaskolb/SwagGen
//

import Foundation

extension Request {

    /**
        Delete Event Handler.

        Deletes the specified event handler.

        Docs: https://dev.soracom.io/en/docs/api/#!/EventHandler/deleteEventHandler
    */
    public class func _deleteEventHandler(
        
        handlerId: String,
        responseHandler: ResponseHandler<NoResponseBody>? = nil
    ) ->   Request<NoResponseBody> {

        let path  = "/event_handlers/\(handlerId)"

        let requestObject = Request<NoResponseBody>.init(path, responseHandler: responseHandler)

        
        requestObject.expectedHTTPStatus = 204
        requestObject.method = .delete


        return requestObject
    }

}
