//
// Generated by SwagGen
// https://github.com/yonaskolb/SwagGen
//

import Foundation

extension Request {

    public class func _listEventHandlersBySubscriber(
        
        imsi: String,
        responseHandler: ResponseHandler<[EventHandlerModel]>? = nil
    ) ->   Request<[EventHandlerModel]> {

        let path = "/event_handlers/subscribers/{imsi}".replacingOccurrences(of: "{" + "imsi" + "}", with: "\(imsi)") // This nonsense should be fixed in the code generator, we might do a PR for at some point...

        let requestObject = Request<[EventHandlerModel]>.init(path, responseHandler: responseHandler)

        
        requestObject.expectedHTTPStatus = 200
        requestObject.method = .get


        return requestObject
    }

}
