//
// Generated by SwagGen
// https://github.com/yonaskolb/SwagGen
//

import Foundation

extension Request where T == ListProductResponse {

    /**
        List products.

        Returns a list of products.

        [API Documentation](https://dev.soracom.io/en/docs/api/#!/Order/listProducts)
    */
    public class func listProducts(
        
        responseHandler: ResponseHandler<ListProductResponse>? = nil
    ) ->   Request<ListProductResponse> {

        let path  = "/products"

        let requestObject = Request<ListProductResponse>.init(path, responseHandler: responseHandler)

        
        requestObject.expectedHTTPStatus = 200
        requestObject.method = .get


        return requestObject
    }

}
