//
// Generated by SwagGen
// https://github.com/yonaskolb/SwagGen
//

import Foundation

extension Request where T == String {

    /**
        Register subscribers for operator.

        Registers the ordered SIM with the operator.

        Docs: https://dev.soracom.io/en/docs/api/#!/Order/registerOrderedSim
    */
    public class func registerOrderedSim(
        
        orderId: String,
        responseHandler: ResponseHandler<String>? = nil
    ) ->   Request<String> {

        let path  = "/orders/\(orderId)/subscribers/register"

        let requestObject = Request<String>.init(path, responseHandler: responseHandler)

        
        requestObject.expectedHTTPStatus = 200
        requestObject.method = .post


        return requestObject
    }

}
