//
// Generated by SwagGen
// https://github.com/yonaskolb/SwagGen
//

import Foundation

extension Request where T == LoraNetworkSet {

    /**
        Revokes a permission from a LoRa network set.

        Revokes a permission and removes an operator from the list of allowed operators in the network set.

        Docs: https://dev.soracom.io/en/docs/api/#!/LoraNetworkSet/revokePermissionFromLoraNetworkSet
    */
    public class func revokePermissionFromLoraNetworkSet(
        operatorId: UpdatePermissionRequest, 
        nsId: String,
        responseHandler: ResponseHandler<LoraNetworkSet>? = nil
    ) ->   Request<LoraNetworkSet> {

        let path  = "/lora_network_sets/\(nsId)/revoke_permission"

        let requestObject = Request<LoraNetworkSet>.init(path, responseHandler: responseHandler)

        requestObject.messageBody = operatorId.toData()
        requestObject.expectedHTTPStatus = 200
        requestObject.method = .post


        return requestObject
    }

}
